import { authorizedMutation,authorizedQuery } from './lib/authorizedServer';
import {mutation,query} from './lib/untypedServer';
import {v} from 'convex/values';
import * as handlers from '../shared/functions/memberGovernance';
import {toPortableMutationCtx,toPortableQueryCtx} from './lib/portable';
export const list=authorizedQuery('memberGovernance:list',query)({args:{societyId:v.id('societies'),memberId:v.optional(v.id('members'))},returns:v.any(),handler:async(ctx,args)=>handlers.list(await toPortableQueryCtx(ctx),args)});
export const observeSeat=authorizedMutation('memberGovernance:observeSeat',mutation)({args:{societyId:v.id('societies'),seatKey:v.string(),organizationName:v.string(),observation:v.any()},returns:v.any(),handler:async(ctx,args)=>handlers.observeSeat(await toPortableMutationCtx(ctx),args)});
export const authorizeSeatProxy=authorizedMutation('memberGovernance:authorizeSeatProxy',mutation)({args:{seatId:v.id('organizationSeats'),meetingId:v.id('meetings'),principalName:v.string(),proxyName:v.string(),authority:v.any(),source:v.any()},returns:v.any(),handler:async(ctx,args)=>handlers.authorizeSeatProxy(await toPortableMutationCtx(ctx),args)});
export const createRule=authorizedMutation('memberGovernance:createRule',mutation)({args:{societyId:v.id('societies'),ruleKey:v.string(),effectiveDate:v.string(),requirements:v.array(v.any()),authority:v.any(),reviewStatus:v.string()},returns:v.any(),handler:async(ctx,args)=>handlers.createRule(await toPortableMutationCtx(ctx),args)});
export const assess=authorizedMutation('memberGovernance:assess',mutation)({args:{memberId:v.id('members'),ruleVersionId:v.id('membershipRuleVersions'),asOf:v.string(),results:v.array(v.any())},returns:v.any(),handler:async(ctx,args)=>handlers.assess(await toPortableMutationCtx(ctx),args)});
export const transition=authorizedMutation('memberGovernance:transition',mutation)({args:{memberId:v.id('members'),assessmentId:v.id('memberAssessments'),status:v.string(),votingRights:v.optional(v.boolean()),source:v.any()},returns:v.any(),handler:async(ctx,args)=>handlers.transition(await toPortableMutationCtx(ctx),args)});

// A2/B1/B2: organization members, seats and representative terms.
const sourceArg=v.object({sourceUrl:v.string(),sourceReference:v.string(),reviewStatus:v.string(),sourceExternalIds:v.optional(v.array(v.string()))});
export const organizationMembers=authorizedQuery('memberGovernance:organizationMembers',query)({args:{societyId:v.id('societies')},returns:v.any(),handler:async(ctx,args)=>handlers.organizationMembers(await toPortableQueryCtx(ctx),args)});
export const seatDetail=authorizedQuery('memberGovernance:seatDetail',query)({args:{seatId:v.id('organizationSeats')},returns:v.any(),handler:async(ctx,args)=>handlers.seatDetail(await toPortableQueryCtx(ctx),args)});
export const saveOrganizationMember=authorizedMutation('memberGovernance:saveOrganizationMember',mutation)({args:{societyId:v.id('societies'),memberId:v.optional(v.id('members')),organizationName:v.string(),membershipClass:v.string(),status:v.string(),joinedAt:v.string(),leftAt:v.optional(v.string()),votingRights:v.boolean(),email:v.optional(v.string()),notes:v.optional(v.string()),linkSeatIds:v.optional(v.array(v.id('organizationSeats')))},returns:v.any(),handler:async(ctx,args)=>handlers.saveOrganizationMember(await toPortableMutationCtx(ctx),args)});
export const updateSeat=authorizedMutation('memberGovernance:updateSeat',mutation)({args:{seatId:v.id('organizationSeats'),memberId:v.optional(v.union(v.id('members'),v.null())),committeeId:v.optional(v.union(v.id('committees'),v.null())),rosterSheet:v.optional(v.string()),status:v.optional(v.string()),notes:v.optional(v.string())},returns:v.any(),handler:async(ctx,args)=>handlers.updateSeat(await toPortableMutationCtx(ctx),args)});
export const addSeat=authorizedMutation('memberGovernance:addSeat',mutation)({args:{societyId:v.id('societies'),organizationName:v.string(),seatKey:v.optional(v.string()),memberId:v.optional(v.id('members')),committeeId:v.optional(v.id('committees')),rosterSheet:v.optional(v.string())},returns:v.any(),handler:async(ctx,args)=>handlers.addSeat(await toPortableMutationCtx(ctx),args)});
export const recordRepresentative=authorizedMutation('memberGovernance:recordRepresentative',mutation)({args:{seatId:v.id('organizationSeats'),personId:v.optional(v.id('peopleDirectory')),personName:v.optional(v.string()),roleTitle:v.optional(v.string()),termStart:v.optional(v.string()),termEnd:v.optional(v.string()),endPreviousObservationId:v.optional(v.string()),notes:v.optional(v.string()),source:sourceArg},returns:v.any(),handler:async(ctx,args)=>handlers.recordRepresentative(await toPortableMutationCtx(ctx),args)});
export const supersedeSeatObservation=authorizedMutation('memberGovernance:supersedeSeatObservation',mutation)({args:{seatId:v.id('organizationSeats'),observationId:v.string(),changes:v.object({personId:v.optional(v.union(v.id('peopleDirectory'),v.null())),personName:v.optional(v.string()),roleTitle:v.optional(v.string()),kind:v.optional(v.string()),termStart:v.optional(v.string()),termEnd:v.optional(v.string()),notes:v.optional(v.string()),reviewStatus:v.optional(v.string())}),rationale:v.string()},returns:v.any(),handler:async(ctx,args)=>handlers.supersedeSeatObservation(await toPortableMutationCtx(ctx),args)});
