import {authorizedMutation,authorizedQuery} from './lib/authorizedServer';import {mutation,query} from './lib/untypedServer';import {v} from 'convex/values';import * as handlers from '../shared/functions/personHistory';import {toPortableMutationCtx,toPortableQueryCtx} from './lib/portable';
const societyId=v.id('societies'),personId=v.id('peopleDirectory');
export const overview=authorizedQuery('personHistory:overview',query)({args:{societyId},returns:v.any(),handler:async(ctx,args)=>handlers.overview(await toPortableQueryCtx(ctx),args)});
export const profile=authorizedQuery('personHistory:profile',query)({args:{societyId,personId,asOf:v.optional(v.string())},returns:v.any(),handler:async(ctx,args)=>handlers.profile(await toPortableQueryCtx(ctx),args)});
export const forRecord=authorizedQuery('personHistory:forRecord',query)({args:{societyId,recordTable:v.string(),recordId:v.string()},returns:v.any(),handler:async(ctx,args)=>handlers.forRecord(await toPortableQueryCtx(ctx),args)});
export const createContact=authorizedMutation('personHistory:createContact',mutation)({args:{societyId,fullName:v.string(),aliases:v.optional(v.array(v.string())),sourceKey:v.optional(v.string())},returns:v.any(),handler:async(ctx,args)=>handlers.createContact(await toPortableMutationCtx(ctx),args)});
export const setAliases=authorizedMutation('personHistory:setAliases',mutation)({args:{societyId,personId,aliases:v.array(v.string()),source:v.any()},returns:v.any(),handler:async(ctx,args)=>handlers.setAliases(await toPortableMutationCtx(ctx),args)});
export const observe=authorizedMutation('personHistory:observe',mutation)({args:{societyId,observation:v.any()},returns:v.any(),handler:async(ctx,args)=>handlers.observe(await toPortableMutationCtx(ctx),args)});
export const reviewMatch=authorizedMutation('personHistory:reviewMatch',mutation)({args:{societyId,occurrenceId:v.id('personOccurrences'),personId:v.optional(personId),status:v.string(),rationale:v.string(),source:v.any(),testOnly:v.optional(v.boolean())},returns:v.any(),handler:async(ctx,args)=>handlers.reviewMatch(await toPortableMutationCtx(ctx),args)});
export const applyTestAssumptions=authorizedMutation('personHistory:applyTestAssumptions',mutation)({args:{societyId,testOnly:v.boolean(),assignments:v.array(v.object({occurrenceId:v.id('personOccurrences'),personId:v.optional(personId),status:v.optional(v.string()),rationale:v.string(),source:v.any(),expectedReviewHistoryLength:v.optional(v.number())}))},returns:v.any(),handler:async(ctx,args)=>handlers.applyTestAssumptions(await toPortableMutationCtx(ctx),args)});
export const stageTestMentions=authorizedMutation('personHistory:stageTestMentions',mutation)({args:{societyId,testOnly:v.boolean(),mentions:v.array(v.object({observation:v.any(),personId:v.optional(personId),rationale:v.string(),note:v.optional(v.object({eventKey:v.string(),title:v.string(),details:v.string(),effectiveDate:v.optional(v.string())}))}))},returns:v.any(),handler:async(ctx,args)=>handlers.stageTestMentions(await toPortableMutationCtx(ctx),args)});
export const addEvent=authorizedMutation('personHistory:addEvent',mutation)({args:{societyId,personId,event:v.any()},returns:v.any(),handler:async(ctx,args)=>handlers.addEvent(await toPortableMutationCtx(ctx),args)});
export const reviewEvent=authorizedMutation('personHistory:reviewEvent',mutation)({args:{societyId,eventId:v.id('personHistoryEvents'),status:v.string(),rationale:v.string()},returns:v.any(),handler:async(ctx,args)=>handlers.reviewEvent(await toPortableMutationCtx(ctx),args)});
export const stageRecord=authorizedMutation('personHistory:stageRecord',mutation)({args:{societyId,recordTable:v.string(),recordId:v.string(),sourceUrl:v.string(),sourceReference:v.string()},returns:v.any(),handler:async(ctx,args)=>handlers.stageRecord(await toPortableMutationCtx(ctx),args)});
export const addContactPoint=authorizedMutation('personHistory:addContactPoint',mutation)({args:{societyId,personId,point:v.any()},returns:v.any(),handler:async(ctx,args)=>handlers.addContactPoint(await toPortableMutationCtx(ctx),args)});

// WP-H: identity maintenance (merge, duplicate suggestions, re-link repair, fragment split).
export const duplicateSuggestions=authorizedQuery('personHistory:duplicateSuggestions',query)({args:{societyId,minScore:v.optional(v.number())},returns:v.any(),handler:async(ctx,args)=>(await import('../shared/functions/personMerge')).duplicateSuggestions(await toPortableQueryCtx(ctx),args)});
export const mergeHistory=authorizedQuery('personHistory:mergeHistory',query)({args:{societyId,personId:v.optional(personId)},returns:v.any(),handler:async(ctx,args)=>(await import('../shared/functions/personMerge')).mergeHistory(await toPortableQueryCtx(ctx),args)});
export const dismissDuplicate=authorizedMutation('personHistory:dismissDuplicate',mutation)({args:{societyId,personIds:v.array(personId),rationale:v.string()},returns:v.any(),handler:async(ctx,args)=>(await import('../shared/functions/personMerge')).dismissDuplicate(await toPortableMutationCtx(ctx),args)});
export const mergePeople=authorizedMutation('personHistory:mergePeople',mutation)({args:{societyId,survivorId:personId,mergedIds:v.array(personId),rationale:v.string(),keepNameAsAlias:v.optional(v.boolean())},returns:v.any(),handler:async(ctx,args)=>(await import('../shared/functions/personMerge')).mergePeople(await toPortableMutationCtx(ctx),args)});
export const unmergePeople=authorizedMutation('personHistory:unmergePeople',mutation)({args:{societyId,mergeId:v.id('personMerges'),notes:v.optional(v.string())},returns:v.any(),handler:async(ctx,args)=>(await import('../shared/functions/personMerge')).unmergePeople(await toPortableMutationCtx(ctx),args)});
export const repairOrphanedEvents=authorizedMutation('personHistory:repairOrphanedEvents',mutation)({args:{societyId,dryRun:v.optional(v.boolean())},returns:v.any(),handler:async(ctx,args)=>(await import('../shared/functions/personMerge')).repairOrphanedEvents(await toPortableMutationCtx(ctx),args)});
export const splitOccurrence=authorizedMutation('personHistory:splitOccurrence',mutation)({args:{societyId,occurrenceId:v.id('personOccurrences'),parts:v.array(v.object({personName:v.string(),personId:v.optional(personId),roleTitle:v.optional(v.string()),affiliation:v.optional(v.string())})),rationale:v.string()},returns:v.any(),handler:async(ctx,args)=>(await import('../shared/functions/personMerge')).splitOccurrence(await toPortableMutationCtx(ctx),args)});
export const createPersonFromOccurrence=authorizedMutation('personHistory:createPersonFromOccurrence',mutation)({args:{societyId,occurrenceId:v.id('personOccurrences'),fullName:v.string(),rationale:v.string()},returns:v.any(),handler:async(ctx,args)=>(await import('../shared/functions/personMerge')).createPersonFromOccurrence(await toPortableMutationCtx(ctx),args)});
