import { test, expect } from "@playwright/test";
import { completeGuidedOrganizationSetup } from "./helpers/guidedSetup";

test.setTimeout(100_000);
test("an unavailable rich-editor chunk leaves a real local deadline draft editable and persistent", async ({ page }) => {
  let blocked = 0;
  await page.route(/\/src\/components\/MarkdownEditorImpl\.tsx(?:\?|$)/, (route) => { blocked += 1; return route.abort(); });
  await page.goto("/setup");
  await page.getByRole("button", { name: /Start a new organization/i }).click();
  await completeGuidedOrganizationSetup(page, "Offline editor fallback workspace", true);
  await expect(page.locator(".app-shell")).toBeVisible();
  await page.goto("/app/deadlines");
  await page.getByRole("button", { name: "New deadline", exact: true }).click();
  let drawer = page.getByRole("dialog", { name: "Add deadline", exact: true });
  await drawer.getByLabel("Title", { exact: true }).fill("Offline fallback evidence");
  const text = "# Offline draft\n\n**Evidence retained after an unavailable rich-editor download.**";
  await expect(drawer.getByRole("status")).toContainText("You can edit and save Markdown text below");
  await drawer.getByRole("textbox", { name: "Markdown text", exact: true }).fill(text);
  await drawer.getByRole("button", { name: "Save", exact: true }).click();
  await expect(drawer).toBeHidden();
  expect(blocked).toBeGreaterThan(0);
  await page.reload();
  await page.getByRole("button", { name: "Calendar", exact: true }).click();
  await page.locator(".calendar-view").getByRole("button", { name: "List", exact: true }).click();
  await page.locator(".calendar-view").getByRole("button", { name: "Offline fallback evidence", exact: true }).click();
  drawer = page.getByRole("dialog", { name: "Edit deadline", exact: true });
  await expect(drawer.getByRole("textbox", { name: "Markdown text", exact: true })).toHaveValue(text);
  const edited = `${text}\n\nAmended locally.`;
  await drawer.getByRole("textbox", { name: "Markdown text", exact: true }).fill(edited);
  await drawer.getByRole("button", { name: "Save", exact: true }).click();
  await expect(drawer).toBeHidden();
  await page.reload();
  await page.getByRole("button", { name: "Calendar", exact: true }).click();
  await page.locator(".calendar-view").getByRole("button", { name: "List", exact: true }).click();
  await page.locator(".calendar-view").getByRole("button", { name: "Offline fallback evidence", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Edit deadline", exact: true }).getByRole("textbox", { name: "Markdown text", exact: true })).toHaveValue(edited);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});

test("a failed rich-editor import keeps Viewer fallback text read-only", async ({ page }) => {
  await page.clock.setFixedTime(new Date("2026-04-18T20:00:00Z"));
  await page.route(/\/src\/components\/MarkdownEditorImpl\.tsx(?:\?|$)/, (route) => route.abort());
  await page.goto("/demo/app/users");
  await page.getByRole("button", { name: "Add user", exact: true }).click();
  const form = page.getByRole("dialog", { name: "Add user", exact: true });
  await form.getByLabel("Display name", { exact: true }).fill("Fallback Viewer");
  await form.getByLabel("Email", { exact: true }).fill("fallback-viewer@interface.example");
  await form.getByLabel("Role", { exact: true }).click();
  await page.getByRole("option", { name: "Viewer", exact: true }).click();
  await form.getByRole("button", { name: "Save", exact: true }).click();
  await expect(form).toBeHidden();
  const picker = page.getByTitle("Switch acting user", { exact: true });
  if (!await picker.isVisible()) await page.locator(".bottom-nav").getByRole("button", { name: "More", exact: true }).click();
  await picker.click();
  await page.locator("span").filter({ hasText: /^Fallback Viewer$/ }).click();
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Search", exact: true }).click();
  const palette = page.getByRole("dialog", { name: "Command palette", exact: true });
  await palette.getByRole("combobox").fill("Deadlines");
  await palette.getByRole("option", { name: /^Deadlines/ }).first().click();
  await page.getByRole("button", { name: "Calendar", exact: true }).click();
  await page.locator(".calendar-view").getByRole("button", { name: "File annual report", exact: true }).click();
  const drawer = page.getByRole("dialog", { name: "View deadline", exact: true });
  const text = drawer.getByRole("textbox", { name: "Markdown text", exact: true });
  await expect(text).toHaveAttribute("readonly", "");
  await expect(text).toBeDisabled();
  await expect(drawer.getByRole("button", { name: "Save", exact: true })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});
