import { expect, test } from "@playwright/test";

test("Viewer can inspect configuration without editing fields, publication or archive settings", async ({ page }) => {
  test.setTimeout(70_000);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/demo/app/users");
  await page.getByRole("button", { name: "Add user", exact: true }).click();
  const form = page.getByRole("dialog", { name: "Add user", exact: true });
  await form.getByLabel("Display name", { exact: true }).fill("Configuration Viewer");
  await form.getByLabel("Email", { exact: true }).fill("configuration-viewer@interface.example");
  await form.getByLabel("Role", { exact: true }).click();
  await page.getByRole("option", { name: "Viewer", exact: true }).click();
  await form.getByRole("button", { name: "Save", exact: true }).click();
  await expect(form).toBeHidden();
  const picker = page.getByTitle("Switch acting user", { exact: true });
  const chooseActor = async (name: string) => {
    if (!await picker.isVisible()) await page.locator(".bottom-nav").getByRole("button", { name: "More", exact: true }).click();
    await picker.click();
    await page.locator("span").filter({ hasText: new RegExp(`^${name}$`) }).click();
    if (page.viewportSize()!.width < 980) await page.keyboard.press("Escape");
  };
  const navigate = async (name: string) => {
    await page.getByRole("button", { name: "Search", exact: true }).click();
    const palette = page.getByRole("dialog", { name: "Command palette", exact: true });
    await palette.getByRole("combobox").fill(name);
    await palette.getByRole("option", { name: new RegExp(`^${name}`) }).first().click();
    await expect(palette).toBeHidden();
  };
  await chooseActor("Configuration Viewer");
  await navigate("Custom fields");
  await expect(page.getByRole("button", { name: "New field", exact: true })).toBeDisabled();
  await expect(page.locator(".record-table__cell--editable")).toHaveCount(0);
  await navigate("Public transparency");
  await expect(page.getByRole("button", { name: "New draft", exact: true })).toBeDisabled();
  await expect(page.locator(".transparency-builder__preset").first()).toBeDisabled();
  await page.getByRole("button", { name: "More actions", exact: true }).click();
  await expect(page.getByRole("menuitem", { name: "Edit settings", exact: true })).toHaveAttribute("aria-disabled", "true");
  await page.keyboard.press("Escape");
  await navigate("Paperless");
  await expect(page.getByRole("button", { name: "Test", exact: true })).toBeDisabled();
  await expect(page.getByLabel("Tag prefix", { exact: true })).toBeDisabled();
  await expect(page.getByRole("switch").first()).toBeDisabled();
  await chooseActor("Owner");
  if (!await picker.isVisible()) await page.locator(".bottom-nav").getByRole("button", { name: "More", exact: true }).click();
  await picker.click();
  const choices = page.getByRole("listbox", { name: "Acting user", exact: true });
  await expect(choices.getByRole("option", { selected: true })).toBeFocused();
  await page.keyboard.press("End");
  await expect(choices.getByRole("option").last()).toBeFocused();
  await page.keyboard.press("Home");
  await expect(choices.getByRole("option").first()).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(choices).toBeHidden();
  await expect(picker).toBeFocused();
  if (page.viewportSize()!.width < 980) await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "Test", exact: true })).toBeEnabled();
  await expect(page.getByLabel("Tag prefix", { exact: true })).toBeEnabled();
  expect(errors).toEqual([]);
});
