import { test, expect } from "@playwright/test";

test("election creation hands off to a complete editable draft and freezes its ballot when opened", async ({ page }) => {
  test.setTimeout(90_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/demo/app/elections");
  await page.getByRole("button", { name: "New election", exact: true }).click();
  const drawer = page.getByRole("dialog", { name: "New election", exact: true });
  await expect(drawer.getByRole("button", { name: "Save", exact: true })).toBeDisabled();
  await drawer.getByLabel("Election title", { exact: true }).fill("Integrated governance election");
  await expect(drawer.getByRole("button", { name: "Save", exact: true })).toBeDisabled();
  await drawer.getByPlaceholder("Option 1", { exact: true }).fill("Candidate A");
  await drawer.getByPlaceholder("Option 2", { exact: true }).fill("Candidate B");
  await drawer.getByRole("button", { name: "Save", exact: true }).click();
  await expect(drawer).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Integrated governance election", exact: true })).toBeVisible();
  await expect(page.getByRole("radio", { name: "Candidate A", exact: true })).toBeVisible();
  await page.getByLabel("New ballot question", { exact: true }).fill("Choose the venue");
  await page.getByLabel("Ballot options", { exact: true }).fill("Hall\nOnline");
  await page.getByRole("button", { name: "Add ballot question", exact: true }).click();
  await expect(page.getByText("Choose the venue", { exact: true }).first()).toBeVisible();
  await expect(page.getByRole("radio", { name: "Online", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(await page.locator(".page").last().evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  await page.getByRole("button", { name: "Snapshot + open", exact: true }).click();
  await expect(page.getByRole("button", { name: "Close election", exact: true })).toBeVisible();
  await expect(page.getByLabel("New ballot question", { exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Snapshot + open", exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole("heading", { name: "Integrated governance election", exact: true })).toBeVisible();
  await expect(page.getByRole("radio", { name: "Candidate A", exact: true })).toBeVisible();
  await expect(page.getByRole("radio", { name: "Online", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Close election", exact: true }).click();
  await page.getByRole("button", { name: "Publish results", exact: true }).click();
  await expect(page.getByRole("button", { name: "Close election", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Publish results", exact: true })).toHaveCount(0);
  expect(errors).toEqual([]);
});
