import { expect, test } from '@playwright/test';
import { completeGuidedOrganizationSetup } from './helpers/guidedSetup';
test.setTimeout(140_000);

test('detailed annual filing links into the annual ledger, records manual evidence and persists without duplicate rows', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/setup');
  await page.getByRole('button', { name: /Start a new organization/i }).click();
  await completeGuidedOrganizationSetup(page, `Filing ledger ${testInfo.project.name}`, true);
  await page.goto('/app/filings');
  await page.getByRole('button', { name: 'New filing', exact: true }).click();
  await page.getByLabel('Period / label', { exact: true }).fill('2026');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Mark filed', exact: true })).toBeVisible();
  await page.goto('/app/annual-filings');
  await page.getByRole('button', { name: 'Add filing', exact: true }).click();
  const select = page.getByLabel('Detailed annual filing', { exact: true });
  await expect(select.locator('option')).toHaveCount(2);
  await select.selectOption({ label: 'BCSocietyAnnualReport · CA-BC · 2026 · Upcoming' });
  await expect(page.getByLabel('Jurisdiction', { exact: true })).toHaveValue('CA-BC');
  await expect(page.getByLabel('Year', { exact: true })).toHaveValue('2026');
  await expect(page.getByLabel('Year', { exact: true })).toBeDisabled();
  await expect(page.getByRole('checkbox')).toBeDisabled();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const region = page.getByRole('region', { name: 'CA-BC annual filing records', exact: true });
  await expect(region.locator('tbody tr')).toHaveCount(1);
  await expect(region).toContainText('✗');
  await page.goto('/app/filings');
  await page.getByRole('button', { name: 'Mark filed', exact: true }).click();
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByText('Add filed date, method, and at least one evidence item before marking filed')).toBeVisible();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByLabel('Confirmation number', { exact: true }).fill('Synthetic manual confirmation; no actual external submission');
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.goto('/app/annual-filings');
  await expect(region).toContainText('✓');
  await expect(region).toContainText('Linked record');
  await page.reload();
  await expect(region.locator('tbody tr')).toHaveCount(1);
  await expect(region).toContainText('✓');
  await page.getByRole('button', { name: 'Add filing', exact: true }).click();
  await page.getByLabel('Detailed annual filing', { exact: true }).selectOption({ label: 'BCSocietyAnnualReport · CA-BC · 2026 · Filed' });
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(region.locator('tbody tr')).toHaveCount(1);
  await expect(page.getByText(/neither verifies government acceptance/)).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});
