/**
 * PORTABLE FUNCTIONS: the tasks domain
 * (list / byCommittee / byGoal / byMeeting / create / update / remove).
 *
 * Reads/writes the `tasks` table (and logs to `activity`) over `ctx.db`. Each
 * handler runs unchanged on hosted Convex, the local Dexie runtime, and the
 * convex-test oracle.
 */

import type { PortableMutationCtx, PortableQueryCtx } from "../portable/ctx";
import { getOwned, principalUserId, requireSocietyMembership } from "./access";
import { HISTORICAL_ACTION_TAG, PROMOTED_ACTION_TAG, TASK_STATUSES, actionTitleKey, isHistoricalSourceAction, sourceAssigneeFromTitle } from "../taskStatus";

/** B6: an agenda item must belong to the task's meeting (or any meeting of the society when none is set). */
async function assertAgendaItem(ctx: PortableMutationCtx, agendaItemId: string, societyId: string, meetingId?: string) {
  const item = await getOwned(ctx, "agendaItems", agendaItemId, societyId);
  if (meetingId) {
    const agenda = await ctx.db.get(String(item.agendaId), "agendas");
    if (!agenda || agenda.meetingId !== meetingId) throw new Error("The agenda item belongs to a different meeting.");
  }
}

/** Correlation keys generated by other modules still bind to an owned source row. */
async function assertTaskEventReference(ctx: PortableMutationCtx, eventId: string, societyId: string) {
  const markers = [
    ["commitment:", "commitments"],
    ["workflowPackage:", "workflowPackages"],
    ["policy-signatures:", "policies"],
    ["policy:", "policies"],
  ] as const;
  for (const [prefix, table] of markers) {
    if (eventId.startsWith(prefix)) {
      await getOwned(ctx, table, eventId.slice(prefix.length), societyId);
      return;
    }
  }
  if (eventId.startsWith("boardPack:")) {
    // Split at the final colon: local runtime IDs may themselves contain colons.
    const source = eventId.slice("boardPack:".length);
    const separator = source.lastIndexOf(":");
    const step = source.slice(separator + 1);
    if (separator < 1 || !/^[a-z][a-z0-9-]*$/.test(step)) throw new Error("Invalid board-pack event reference.");
    await getOwned(ctx, "workflowPackages", source.slice(0, separator), societyId);
    return;
  }
  // Legacy completion IDs are actual commitmentEvents rows, including their parent.
  // Unknown namespaces and arbitrary external strings do not gain an ownership bypass.
  const event = await getOwned(ctx, "commitmentEvents", eventId, societyId);
  await getOwned(ctx, "commitments", String(event.commitmentId), societyId);
}

export async function tasksList(ctx: PortableQueryCtx, { societyId }: { societyId: string }) {
  await requireSocietyMembership(ctx, societyId);
  return ctx.db
    .query("tasks")
    .withIndex("by_society", (q) => q.eq("societyId", societyId))
    .collect();
}

export async function tasksByCommittee(ctx: PortableQueryCtx, { committeeId }: { committeeId: string }) {
  const committee = await ctx.db.get(committeeId, "committees");
  if (!committee || typeof committee.societyId !== "string") throw new Error("committees not found.");
  await requireSocietyMembership(ctx, committee.societyId);
  await getOwned(ctx, "committees", committeeId, committee.societyId);
  return ctx.db
    .query("tasks")
    .withIndex("by_committee", (q) => q.eq("committeeId", committeeId))
    .collect();
}

export async function tasksByGoal(ctx: PortableQueryCtx, { goalId }: { goalId: string }) {
  const goal = await ctx.db.get(goalId, "goals");
  if (!goal || typeof goal.societyId !== "string") throw new Error("goals not found.");
  await requireSocietyMembership(ctx, goal.societyId);
  await getOwned(ctx, "goals", goalId, goal.societyId);
  return ctx.db
    .query("tasks")
    .withIndex("by_goal", (q) => q.eq("goalId", goalId))
    .collect();
}

export async function tasksByMeeting(ctx: PortableQueryCtx, { meetingId }: { meetingId: string }) {
  const meeting = await ctx.db.get(meetingId, "meetings");
  if (!meeting || typeof meeting.societyId !== "string") throw new Error("meetings not found.");
  await requireSocietyMembership(ctx, meeting.societyId);
  await getOwned(ctx, "meetings", meetingId, meeting.societyId);
  return ctx.db
    .query("tasks")
    .withIndex("by_meeting", (q) => q.eq("meetingId", meetingId))
    .collect();
}

export async function taskCreate(
  ctx: PortableMutationCtx,
  args: {
    societyId: string;
    title: string;
    description?: string;
    status: string;
    priority: string;
    assignee?: string;
    /** A1: the responsible person in the people directory. */
    assigneePersonId?: string;
    /** The assignee exactly as the source wrote it ("TG", "Gail / Deanna"). */
    sourceAssignee?: string;
    responsibleUserIds?: string[];
    dueDate?: string;
    committeeId?: string;
    meetingId?: string;
    agendaItemId?: string;
    goalId?: string;
    filingId?: string;
    workflowId?: string;
    documentId?: string;
    commitmentId?: string;
    eventId?: string;
    tags: string[];
  },
): Promise<string> {
  await requireSocietyMembership(ctx, args.societyId);
  if (!(TASK_STATUSES as readonly string[]).includes(args.status)) throw new Error(`Unknown task status "${args.status}".`);
  if (args.agendaItemId) await assertAgendaItem(ctx, args.agendaItemId, args.societyId, args.meetingId);
  if (args.assigneePersonId) await getOwned(ctx, "peopleDirectory", args.assigneePersonId, args.societyId);
  if (args.committeeId) await getOwned(ctx, "committees", args.committeeId, args.societyId);
  if (args.meetingId) await getOwned(ctx, "meetings", args.meetingId, args.societyId);
  if (args.goalId) await getOwned(ctx, "goals", args.goalId, args.societyId);
  if (args.filingId) await getOwned(ctx, "filings", args.filingId, args.societyId);
  if (args.workflowId) await getOwned(ctx, "workflows", args.workflowId, args.societyId);
  if (args.documentId) await getOwned(ctx, "documents", args.documentId, args.societyId);
  if (args.commitmentId) await getOwned(ctx, "commitments", args.commitmentId, args.societyId);
  if (args.eventId) await assertTaskEventReference(ctx, args.eventId, args.societyId);
  for (const userId of args.responsibleUserIds ?? []) {
    await getOwned(ctx, "users", userId, args.societyId);
  }
  const id = await ctx.db.insert("tasks", {
    ...args,
    createdAtISO: new Date().toISOString(),
  });
  await ctx.db.insert("activity", {
    societyId: args.societyId,
    actor: "You",
    entityType: "task",
    subjectId: id,
    // TODO(H0-flip): drop the legacy semantic mirror once all readers use subjectId indexes.
    entityId: id,
    action: "created",
    summary: `Created task "${args.title}"`,
    createdAtISO: new Date().toISOString(),
  });
  return id;
}

export async function taskUpdate(
  ctx: PortableMutationCtx,
  { id, patch }: {
    id: string;
    patch: {
      title?: string;
      description?: string;
      status?: string;
      priority?: string;
      assignee?: string;
      assigneePersonId?: string;
      clearAssigneePersonId?: boolean;
      sourceAssignee?: string;
      responsibleUserIds?: string[];
      dueDate?: string;
      committeeId?: string;
      meetingId?: string;
      agendaItemId?: string;
      clearAgendaItemId?: boolean;
      goalId?: string;
      filingId?: string;
      workflowId?: string;
      documentId?: string;
      commitmentId?: string;
      eventId?: string;
      tags?: string[];
      completedAt?: string;
      completedByUserId?: string;
      completionNote?: string;
      clearMeetingId?: boolean;
    };
  },
): Promise<void> {
  const candidate = await ctx.db.get(id, "tasks");
  if (!candidate || typeof candidate.societyId !== "string") throw new Error("tasks not found.");
  await requireSocietyMembership(ctx, candidate.societyId);
  const task = await getOwned(ctx, "tasks", id, candidate.societyId);
  if (patch.committeeId) await getOwned(ctx, "committees", patch.committeeId, candidate.societyId);
  if (patch.assigneePersonId) await getOwned(ctx, "peopleDirectory", patch.assigneePersonId, candidate.societyId);
  if (patch.meetingId) await getOwned(ctx, "meetings", patch.meetingId, candidate.societyId);
  if (patch.goalId) await getOwned(ctx, "goals", patch.goalId, candidate.societyId);
  if (patch.filingId) await getOwned(ctx, "filings", patch.filingId, candidate.societyId);
  if (patch.workflowId) await getOwned(ctx, "workflows", patch.workflowId, candidate.societyId);
  if (patch.documentId) await getOwned(ctx, "documents", patch.documentId, candidate.societyId);
  if (patch.commitmentId) await getOwned(ctx, "commitments", patch.commitmentId, candidate.societyId);
  if (patch.eventId) await assertTaskEventReference(ctx, patch.eventId, candidate.societyId);
  if (patch.status && !(TASK_STATUSES as readonly string[]).includes(patch.status)) throw new Error(`Unknown task status "${patch.status}".`);
  if (patch.agendaItemId) await assertAgendaItem(ctx, patch.agendaItemId, candidate.societyId, patch.clearMeetingId ? undefined : patch.meetingId ?? task.meetingId);
  for (const userId of patch.responsibleUserIds ?? []) {
    await getOwned(ctx, "users", userId, candidate.societyId);
  }
  const { clearMeetingId, clearAssigneePersonId, clearAgendaItemId, ...rest } = patch;
  const next: Record<string, unknown> = { ...rest };
  if (clearAgendaItemId || clearMeetingId) next.agendaItemId = undefined;
  if (clearAssigneePersonId) next.assigneePersonId = undefined;
  // `undefined` fields are stripped from the wire, so unlinking arrives as an
  // explicit flag and is converted to an unset here.
  if (clearMeetingId) next.meetingId = undefined;
  if (patch.status && patch.status !== task.status) next.statusHistory = [...(task.statusHistory ?? []), {
    from: task.status, to: patch.status, recordedAtISO: new Date().toISOString(), actorUserId: await principalUserId(ctx, candidate.societyId),
    completionNote: patch.completionNote ?? task.completionNote, priorCompletedAt: task.completedAt,
  }];
  if (patch.status === "Done" && !task.completedAt) {
    next.completedAt = new Date().toISOString();
  }
  if (patch.status === "Done" || patch.completedByUserId) {
    next.completedByUserId = await principalUserId(ctx, candidate.societyId);
  }
  if (patch.status && patch.status !== "Done" && task.completedAt) {
    next.completedAt = undefined;
    next.completedByUserId = undefined;
    next.completionNote = undefined;
  }
  await ctx.db.patch(id, next);
  if (patch.status) {
    await ctx.db.insert("activity", {
      societyId: task.societyId,
      actor: "You",
      entityType: "task",
      subjectId: id,
      // TODO(H0-flip): drop the legacy semantic mirror once all readers use subjectId indexes.
      entityId: id,
      action: patch.status === "Done" ? "completed" : "updated",
      summary: `${patch.status === "Done" ? "Completed" : "Moved"} task "${task.title}" → ${patch.status}`,
      createdAtISO: new Date().toISOString(),
    });
  }
}

export async function taskRemove(ctx: PortableMutationCtx, { id }: { id: string }): Promise<void> {
  const candidate = await ctx.db.get(id, "tasks");
  if (!candidate || typeof candidate.societyId !== "string") throw new Error("tasks not found.");
  await requireSocietyMembership(ctx, candidate.societyId);
  await getOwned(ctx, "tasks", id, candidate.societyId);
  await ctx.db.delete(id);
}

/** A rolling source action reuses the canonical task, scoped to its register. */
export async function observeAction(ctx: PortableMutationCtx, args: { societyId: string; registerKey: string; externalActionId: string; title: string; observation: any }) {
  await requireSocietyMembership(ctx, args.societyId);
  const { requirePermissionPortable } = await import('./permissions');
  await requirePermissionPortable(ctx, args.societyId, 'tasks:write');
  const { requireEvidence, partialDate, exactDay } = await import('../evidenceReview');
  const row = args.observation;
  requireEvidence(row);
  if (!row.id || !partialDate(row.observedDate) || !row.observedDate) throw new Error('A stable observation ID and source date are required.');
  if (!['pending','verified','rejected'].includes(row.reviewStatus)) throw new Error('Invalid observation review status.');
  if (row.mappedStatus && !(TASK_STATUSES as readonly string[]).includes(row.mappedStatus)) throw new Error('Invalid mapped task status.');
  const registerKey = args.registerKey.trim(); const externalActionId = args.externalActionId.trim();
  if (!registerKey || !externalActionId || !args.title.trim()) throw new Error('Register, external action ID and title are required.');
  const tasks = await ctx.db.query('tasks').withIndex('by_society', q => q.eq('societyId', args.societyId)).collect();
  // A carried-forward duplicate folded into another task still resolves to it (P5).
  let task: any = tasks.find(item => item.actionRegisterKey === registerKey && (item.externalActionId === externalActionId || item.mergedExternalActionIds?.includes(externalActionId)));
  const history = task?.sourceObservations ?? [];
  const duplicate = history.find((item: any) => item.id === row.id);
  if (duplicate) {
    if (JSON.stringify(duplicate) !== JSON.stringify(row)) throw new Error('Conflicting observation ID. Append a new observation instead.');
    return task._id;
  }
  if (row.meetingId) await getOwned(ctx, 'meetings', row.meetingId, args.societyId);
  if (!task) {
    const id = await taskCreate(ctx, { societyId: args.societyId, title: args.title.trim(), status: 'Todo', priority: 'Medium', tags: ['source-action-register'] });
    task = await ctx.db.get(id, 'tasks');
  }
  const observations = [...history, row];
  const verified = observations.filter((item: any) => item.reviewStatus === 'verified' && exactDay(item.observedDate) && item.mappedStatus);
  const latest = verified.map((item: any) => item.observedDate).sort().at(-1);
  const latestRows = verified.filter((item: any) => item.observedDate === latest);
  const unambiguous = latestRows.length && new Set(latestRows.map((item: any) => item.mappedStatus)).size === 1;
  const patch: any = { actionRegisterKey: registerKey, externalActionId, sourceObservations: observations, sourceStatusReview: unambiguous ? 'verified' : 'needs_review' };
  if (unambiguous) {
    patch.status = latestRows[0].mappedStatus;
    patch.sourceStatusDate = latest;
    patch.completedAt = patch.status === 'Done' ? latest : undefined;
    patch.completedByUserId = patch.status === 'Done' ? await principalUserId(ctx, args.societyId) : undefined;
  }
  await ctx.db.patch(task._id, patch);
  return task._id;
}

/* ------------------- P2–P5: historical source actions ------------------- */

type ConsolidateOptions = { dedupe?: boolean; unknownStatus?: boolean; assignees?: boolean; committees?: boolean };

/** A historical action nobody has acted on since import (safe to fold or re-status). */
function untouchedHistorical(task: any) {
  return isHistoricalSourceAction(task) && !task.completedAt && !(task.statusHistory ?? []).length && ["Todo", "Unknown"].includes(task.status);
}

/**
 * Separate imported minutes actions from current work:
 * - fold carried-forward duplicates (same normalized wording) into the earliest
 *   task, keeping every source observation and external action id;
 * - give unreviewed historical actions the status Unknown (not open work) and
 *   drop the importer's placeholder responsible user;
 * - record the owner named in the action line as `sourceAssignee`;
 * - carry the committee of the source meeting onto the task.
 * Tasks a person already changed are left alone. Dry run by default.
 */
export async function consolidateHistoricalActions(ctx: PortableMutationCtx, args: { societyId: string; dryRun?: boolean; options?: ConsolidateOptions }) {
  await requireSocietyMembership(ctx, args.societyId);
  const { requirePermissionPortable } = await import("./permissions");
  await requirePermissionPortable(ctx, args.societyId, "tasks:write");
  const options = { dedupe: true, unknownStatus: true, assignees: true, committees: true, ...(args.options ?? {}) };
  const dryRun = args.dryRun !== false;
  const all = await ctx.db.query("tasks").withIndex("by_society", (q) => q.eq("societyId", args.societyId)).collect();
  const historical = all.filter(isHistoricalSourceAction);
  const firstDate = (task: any) => (task.sourceObservations ?? []).map((o: any) => String(o.observedDate ?? "")).filter(Boolean).sort()[0] ?? task.createdAtISO;
  const removed = new Set<string>();
  const patches = new Map<string, Record<string, unknown>>();
  const patchFor = (id: string) => { let p = patches.get(id); if (!p) { p = {}; patches.set(id, p); } return p; };
  const duplicateGroups: Array<{ title: string; keep: string; fold: string[] }> = [];
  if (options.dedupe) {
    const groups = new Map<string, any[]>();
    for (const task of historical) {
      const key = `${task.actionRegisterKey ?? ""}::${actionTitleKey(task.title)}`;
      if (!actionTitleKey(task.title)) continue;
      groups.set(key, [...(groups.get(key) ?? []), task]);
    }
    for (const group of groups.values()) {
      if (group.length < 2) continue;
      const sorted = [...group].sort((a, b) => String(firstDate(a)).localeCompare(String(firstDate(b))));
      const keep = sorted.find((task) => !untouchedHistorical(task)) ?? sorted[0];
      const fold = sorted.filter((task) => task._id !== keep._id && untouchedHistorical(task));
      if (!fold.length) continue;
      const seen = new Set((keep.sourceObservations ?? []).map((o: any) => o.id));
      const observations = [...(keep.sourceObservations ?? [])];
      for (const task of fold) for (const o of task.sourceObservations ?? []) if (!seen.has(o.id)) { seen.add(o.id); observations.push({ ...o, foldedFromTaskTitle: task.title }); }
      observations.sort((a: any, b: any) => String(a.observedDate ?? "").localeCompare(String(b.observedDate ?? "")));
      const merged = Array.from(new Set([...(keep.mergedExternalActionIds ?? []), ...fold.map((task) => task.externalActionId).filter(Boolean)]));
      Object.assign(patchFor(keep._id), { sourceObservations: observations, mergedExternalActionIds: merged });
      for (const task of fold) removed.add(task._id);
      duplicateGroups.push({ title: keep.title, keep: keep._id, fold: fold.map((task) => task._id) });
    }
  }
  let unknown = 0, assignees = 0, committees = 0;
  const meetings = new Map<string, any>();
  for (const task of historical) {
    if (removed.has(task._id)) continue;
    if (options.unknownStatus && untouchedHistorical(task) && task.status === "Todo" && task.sourceStatusReview !== "verified") {
      Object.assign(patchFor(task._id), {
        status: "Unknown",
        ...(task.responsibleUserIds?.length ? { responsibleUserIds: [] } : {}),
        statusHistory: [{ from: task.status, to: "Unknown", recordedAtISO: new Date().toISOString(), actorUserId: await principalUserId(ctx, args.societyId), note: "Historical source action: the source does not record completion or a current obligation.", ...(task.responsibleUserIds?.length ? { clearedResponsibleUserIds: task.responsibleUserIds } : {}) }],
      });
      unknown++;
    }
    if (options.assignees && !task.sourceAssignee) {
      const owner = sourceAssigneeFromTitle(task.title.replace(/^Review historical action:\s*/i, ""));
      if (owner) { Object.assign(patchFor(task._id), { sourceAssignee: owner, ...(task.assignee ? {} : { assignee: owner }) }); assignees++; }
    }
    if (options.committees && !task.committeeId && task.meetingId) {
      let meeting = meetings.get(task.meetingId);
      if (meeting === undefined) { meeting = await ctx.db.get(task.meetingId, "meetings"); meetings.set(task.meetingId, meeting ?? null); }
      if (meeting?.committeeId && meeting.societyId === args.societyId) { Object.assign(patchFor(task._id), { committeeId: meeting.committeeId }); committees++; }
    }
  }
  const summary = {
    dryRun,
    historical: historical.length,
    duplicateGroups: duplicateGroups.length,
    folded: removed.size,
    statusUnknown: unknown,
    sourceAssignees: assignees,
    committeesLinked: committees,
    examples: duplicateGroups.slice(0, 10).map((group) => ({ title: group.title, copies: group.fold.length + 1 })),
  };
  if (dryRun) return summary;
  for (const [id, patch] of patches) if (!removed.has(id)) await ctx.db.patch(id, patch);
  for (const id of removed) await ctx.db.delete(id);
  await ctx.db.insert("activity", {
    societyId: args.societyId, actor: "You", entityType: "task", subjectId: args.societyId, entityId: args.societyId, action: "historical_actions_consolidated",
    summary: `Historical source actions: ${removed.size} carried-forward duplicates folded, ${unknown} marked Unknown, ${assignees} source owners recorded, ${committees} committee links`,
    createdAtISO: new Date().toISOString(),
  });
  return summary;
}

/** Turn a historical source action into a current task (P2): keeps the source trail. */
export async function promoteHistoricalAction(ctx: PortableMutationCtx, args: { id: string; title?: string; dueDate?: string; responsibleUserIds?: string[]; note?: string }) {
  const candidate = await ctx.db.get(args.id, "tasks");
  if (!candidate || typeof candidate.societyId !== "string") throw new Error("tasks not found.");
  await requireSocietyMembership(ctx, candidate.societyId);
  const { requirePermissionPortable } = await import("./permissions");
  await requirePermissionPortable(ctx, candidate.societyId, "tasks:write");
  const task = await getOwned(ctx, "tasks", args.id, candidate.societyId);
  if (!isHistoricalSourceAction(task)) throw new Error("This task is already a current task.");
  for (const userId of args.responsibleUserIds ?? []) await getOwned(ctx, "users", userId, candidate.societyId);
  const tags = Array.from(new Set([...(task.tags ?? []).filter((tag: string) => tag !== HISTORICAL_ACTION_TAG && tag !== "needs-source-review"), PROMOTED_ACTION_TAG]));
  await ctx.db.patch(args.id, {
    tags,
    status: "Todo",
    ...(args.title?.trim() ? { title: args.title.trim() } : {}),
    ...(args.dueDate ? { dueDate: args.dueDate } : {}),
    ...(args.responsibleUserIds ? { responsibleUserIds: args.responsibleUserIds } : {}),
    statusHistory: [...(task.statusHistory ?? []), { from: task.status, to: "Todo", recordedAtISO: new Date().toISOString(), actorUserId: await principalUserId(ctx, candidate.societyId), note: `Converted from a historical source action to a current task${args.note ? `: ${args.note}` : ""}.` }],
  });
  await ctx.db.insert("activity", { societyId: task.societyId, actor: "You", entityType: "task", subjectId: args.id, entityId: args.id, action: "promoted", summary: `Converted historical action "${task.title}" to a current task`, createdAtISO: new Date().toISOString() });
  return args.id;
}
