FROM node:22-bookworm-slim AS build

WORKDIR /app

ARG VITE_CONVEX_URL=http://127.0.0.1:3220
ARG VITE_AUTH_MODE=none
ARG VITE_AUTH_BASE_URL=http://127.0.0.1:8080
ARG VITE_CLERK_PUBLISHABLE_KEY
ARG VITE_CLERK_JWT_TEMPLATE=convex
ARG VITE_DOCUMENT_STORAGE_PROVIDER=""
ARG VITE_POWERSYNC_MEETING_PREPARATION=0

ENV VITE_CONVEX_URL=$VITE_CONVEX_URL
ENV VITE_AUTH_MODE=$VITE_AUTH_MODE
ENV VITE_AUTH_BASE_URL=$VITE_AUTH_BASE_URL
ENV VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY
ENV VITE_CLERK_JWT_TEMPLATE=$VITE_CLERK_JWT_TEMPLATE
ENV VITE_DOCUMENT_STORAGE_PROVIDER=$VITE_DOCUMENT_STORAGE_PROVIDER
ENV VITE_POWERSYNC_MEETING_PREPARATION=$VITE_POWERSYNC_MEETING_PREPARATION

COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund

COPY . .
RUN npm run build

FROM nginx:1.25-alpine

COPY docker/frontend.nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 3000
