import {sourceRoleLabel} from '../../shared/personHistory';
import {useState} from 'react';import {Link,useParams} from 'react-router-dom';import {useMutation,useQuery} from 'convex/react';import {api} from '@/lib/convexApi';import {useSociety} from '@/hooks/useSociety';import {usePermissions} from '@/hooks/usePermissions';import {useToast} from '@/components/Toast';import {PageLoading,SeedPrompt} from './_helpers';import {PersonOccurrenceReview} from '@/components/PersonRecordLinks';
export function PersonReviewPage(){
 const society=useSociety();const {can}=usePermissions();const data=useQuery(api.personHistory.overview,society&&can('members:read')?{societyId:society._id}:'skip') as any;
 const [search,setSearch]=useState('');const [status,setStatus]=useState('pending');const [page,setPage]=useState(0);const [name,setName]=useState('');const toast=useToast();const create=useMutation(api.personHistory.createContact);
 if(society===undefined)return <PageLoading/>;if(!society)return <SeedPrompt/>;if(!can('members:read'))return <p>People access required.</p>;if(!data)return <PageLoading/>;
 const query=search.toLocaleLowerCase();const matches=data.occurrences.filter((r:any)=>(status==='all'||(status==='pending'?['suggested','unresolved'].includes(r.matchStatus):r.matchStatus===status))&&[r.personName,r.context,r.affiliation,r.notes].join(' ').toLocaleLowerCase().includes(query));
 return <div className="page"><h1>People, source identities and history</h1><p>Contact profiles connect meeting attendance, notes, roles and affiliations. Source identity suggestions require review; membership and voting rights are assessed separately.</p>
 <p>{data.people.length} contact profiles · {data.occurrences.length} source occurrences · {data.occurrences.filter((r:any)=>r.matchStatus==='verified').length} confirmed identity links</p>
 <div className="row" style={{gap:8,flexWrap:'wrap'}}><input className="input" aria-label="Search people and evidence" placeholder="Search names, affiliations or notes" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/><select className="input" aria-label="Identity review filter" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}>{[['pending','Pending identity review'],['all','All occurrences'],['verified','Confirmed'],['not_person','Organizations and headings'],['rejected','Rejected']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
 <details style={{margin:'16px 0'}}><summary>Person profiles ({data.people.length})</summary><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:8,marginTop:12}}>{data.people.filter((p:any)=>[p.fullName,...(p.aliases??[])].join(' ').toLocaleLowerCase().includes(query)).map((p:any)=><Link key={p._id} to={`/app/people-directory/${p._id}`}>{p.fullName} · {p.occurrences} observations · {p.unreviewed} unreviewed</Link>)}</div></details>
 {can('members:write')&&<details><summary>Create a contact profile</summary><label>Person's name<input className="input" value={name} onChange={e=>setName(e.target.value)}/></label><button className="btn" disabled={!name.trim()} onClick={async()=>{try{await create({societyId:society._id,fullName:name});setName('');toast.success('Contact profile created');}catch(e:any){toast.error(e.message);}}}>Create contact</button></details>}
 <h2>Source identity review ({matches.length})</h2>{matches.slice(page*30,page*30+30).map((row:any)=><PersonOccurrenceReview key={row._id+row.matchStatus} row={row} people={data.people}/>)}<div className="row" style={{gap:12,marginTop:12}}><button className="btn" disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(matches.length/30))}</span><button className="btn" disabled={(page+1)*30>=matches.length} onClick={()=>setPage(page+1)}>Next</button></div>
 </div>;
}
export function PersonProfilePage(){
 const {id}=useParams();const society=useSociety();const {can}=usePermissions();const toast=useToast();const [asOf,setAsOf]=useState('');
 const data=useQuery(api.personHistory.profile,society&&id&&can('members:read')?{societyId:society._id,personId:id,...(asOf?{asOf}:{})}:'skip') as any;
 const addContact=useMutation(api.personHistory.addContactPoint);const [contact,setContact]=useState({kind:'email',value:'',observedDate:'',reviewStatus:'pending',sourceUrl:'',sourceReference:''});
 const reviewEvent=useMutation(api.personHistory.reviewEvent);const add=useMutation(api.personHistory.addEvent);const aliases=useMutation(api.personHistory.setAliases);const [alias,setAlias]=useState('');const [aliasSource,setAliasSource]=useState('');const [aliasCitation,setAliasCitation]=useState('');
 const blank={kind:'observation',title:'',value:'',scope:'general',effectiveDate:'',endDate:'',transition:'observed',details:'',reviewStatus:'pending',sourceUrl:'',sourceReference:'',supersedesEventId:''};const [form,setForm]=useState(blank);const [busy,setBusy]=useState(false);
 if(society===undefined)return <PageLoading/>;if(!society)return <SeedPrompt/>;if(!can('members:read'))return <p>People access required.</p>;if(!data)return <PageLoading/>;
 const field=(key:keyof typeof blank,label:string)=><label>{label}<input className="input" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 return <div className="page"><Link to="/app/people-history">All people and identity reviews</Link><h1>{data.person.fullName}</h1><p>Aliases: {(data.person.aliases??[]).join(', ')||'None confirmed'}</p><p>Source observations retain their wording and dates. Pending identity links are displayed for review. Contact identity alone does not establish membership or voting eligibility.</p>
 <section className="card"><div className="card__body"><h2>Historical role and affiliation</h2><label>As of meeting day<input className="input" aria-label="Historical day" type="date" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label>{data.historical&&['role','affiliation'].map(kind=><p key={kind}>{kind}: <strong>{data.historical[kind].state}</strong> · {data.historical[kind].values.map((v:any)=>`${v.value} (${v.scope})`).join('; ')||'No verified effective interval'}</p>)}<p className="muted">A roster observation applies to its source period. It is not carried back or forward as a confirmed appointment. Changes with month or year precision remain uncertain inside that period.</p></div></section>
 {can('members:write')&&<details className="card" style={{marginTop:16}}><summary className="card__body">Record a dated change or contextual note</summary><div className="card__body col" style={{gap:10}}>
 <label>Kind<select className="input" aria-label="Kind" value={form.kind} onChange={e=>setForm({...form,kind:e.target.value,transition:['role','affiliation'].includes(e.target.value)?'changed':'observed'})}>{['observation','role','affiliation','appointment','departure','note'].map(k=><option key={k}>{k}</option>)}</select></label>
 {field('title','Title')}{field('value','New role or affiliation value')}{field('scope','Organization, committee or role scope')}{field('effectiveDate','Effective source date (YYYY, YYYY-MM or YYYY-MM-DD)')}{field('endDate','End date, if established')}
 <label>Change type<select className="input" value={form.transition} onChange={e=>setForm({...form,transition:e.target.value})}>{['observed','started','changed','ended'].map(k=><option key={k}>{k}</option>)}</select></label>
 <label>Previous event retained in history<select className="input" value={form.supersedesEventId} onChange={e=>setForm({...form,supersedesEventId:e.target.value})}><option value="">No established previous event</option>{data.events.filter((ev:any)=>ev.kind===form.kind&&ev.scope===form.scope).map((ev:any)=><option key={ev._id} value={ev._id}>{ev.effectiveDate} · {ev.title} · {ev.reviewStatus}</option>)}</select></label>
 <label>Context / note<textarea className="input" value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></label>{field('sourceUrl','Source URL')}{field('sourceReference','Page, section or cell citation')}
 <label>Source review<select className="input" value={form.reviewStatus} onChange={e=>setForm({...form,reviewStatus:e.target.value})}>{['pending','verified','rejected'].map(k=><option key={k}>{k}</option>)}</select></label>
 <button className="btn" disabled={busy||!form.title||!form.effectiveDate||!form.sourceReference||!form.sourceUrl} onClick={async()=>{setBusy(true);try{const event:any={...form,eventKey:crypto.randomUUID()};if(!event.endDate)delete event.endDate;if(!event.supersedesEventId)delete event.supersedesEventId;await add({societyId:society._id,personId:id,event});setForm(blank);toast.success('Dated history recorded; earlier evidence retained');}catch(e:any){toast.error(e.message);}finally{setBusy(false);}}}>Save dated event</button>
 </div></details>}
 {can('members:write')&&<details className="card" style={{marginTop:16}}><summary className="card__body">Confirm a name alias</summary><div className="card__body col" style={{gap:8}}><label>Alias<input className="input" value={alias} onChange={e=>setAlias(e.target.value)}/></label><label>Source URL<input className="input" value={aliasSource} onChange={e=>setAliasSource(e.target.value)}/></label><label>Citation<input className="input" value={aliasCitation} onChange={e=>setAliasCitation(e.target.value)}/></label><button className="btn" disabled={!alias||!aliasSource||!aliasCitation} onClick={async()=>{try{await aliases({societyId:society._id,personId:id,aliases:[alias],source:{sourceUrl:aliasSource,sourceReference:aliasCitation,reviewStatus:'verified'}});setAlias('');toast.success('Alias evidence recorded');}catch(e:any){toast.error(e.message);}}}>Add reviewed alias</button></div></details>}
 {!!data.registers?.length&&<section className="card" style={{marginTop:16}}><div className="card__body"><h2>Linked membership and director records</h2>{data.registers.map((r:any)=><div key={r._id}><Link to={r.href}>{r.recordTable==='members'?'Member record':'Director register'}: {r.firstName} {r.lastName}</Link><p>{r.position||r.membershipClass} · {r.status} · {r.termStart||r.joinedAt}{r.termEnd||r.leftAt?` to ${r.termEnd||r.leftAt}`:''}</p>{r.notes&&<p>{r.notes}</p>}</div>)}</div></section>}
 {can('members:write')&&<details className="card" style={{marginTop:16}}><summary className="card__body">Record a dated contact detail</summary><form className="card__body col" style={{gap:8}} onSubmit={async e=>{e.preventDefault();try{await addContact({societyId:society._id,personId:id,point:{...contact,pointKey:crypto.randomUUID()}});setContact({...contact,value:''});toast.success('Dated contact observation saved');}catch(error:any){toast.error(error.message);}}}><label>Contact type<select className="input" value={contact.kind} onChange={e=>setContact({...contact,kind:e.target.value})}>{['email','phone','address','other'].map(k=><option key={k}>{k}</option>)}</select></label>{[['value','Contact value'],['observedDate','Observed source date'],['sourceUrl','Contact source URL'],['sourceReference','Contact source citation']].map(([k,l])=><label key={k}>{l}<input className="input" required value={(contact as any)[k]} onChange={e=>setContact({...contact,[k]:e.target.value})}/></label>)}<label>Contact review<select className="input" value={contact.reviewStatus} onChange={e=>setContact({...contact,reviewStatus:e.target.value})}><option>pending</option><option>verified</option></select></label><button className="btn" type="submit">Save contact observation</button></form></details>}
 {!!data.contactPoints?.length&&<section className="card" style={{marginTop:16}}><div className="card__body"><h2>Contact details observed in sources</h2><p>These values retain their source periods; current contact details require confirmation.</p>{data.contactPoints.map((c:any)=><p key={c._id}>{c.observedDate} · {c.kind}: {c.value} · {c.reviewStatus} · <a href={c.sourceUrl} target="_blank" rel="noreferrer">{c.sourceReference}</a></p>)}</div></section>}
 <h2>Dated history and contextual notes ({data.events.length})</h2>{data.events.map((ev:any)=><article className="card" key={ev._id} style={{marginBottom:8}}><div className="card__body"><strong>{ev.effectiveDate}{ev.endDate?` to ${ev.endDate}`:''} · {ev.title}</strong><p>{ev.kind} · {ev.scope} · {ev.transition} · {ev.reviewStatus}{ev.value?` · ${ev.value}`:''}</p>{ev.details&&<p>{ev.details}</p>}{ev.supersedesEventId&&<p>Previous event retained: {data.events.find((x:any)=>x._id===ev.supersedesEventId)?.title||ev.supersedesEventId}</p>}{ev.sourceUrl&&<a href={ev.sourceUrl} target="_blank" rel="noreferrer">Source</a>} · {ev.sourceReference}{ev.href&&<> · <Link to={ev.href}>Linked member history</Link></>}{can('members:write')&&!ev.derived&&<details style={{marginTop:8}}><summary>Review this history evidence</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await reviewEvent({societyId:society._id,eventId:ev._id,status:String(f.get('status')),rationale:String(f.get('rationale'))});toast.success('History evidence review recorded');}catch(error:any){toast.error(error.message);}}}><label>Review outcome<select name="status" className="input"><option value="verified">Verified against source</option><option value="pending">Pending</option><option value="rejected">Rejected</option></select></label><label>Review rationale<input name="rationale" className="input" required/></label><button className="btn" type="submit">Record review</button></form></details>}{ev.meetingId&&<> · <Link to={`/app/meetings/${ev.meetingId}?tab=minutes`}>Meeting</Link></>}{ev.documentId&&<> · <Link to={`/app/documents/${ev.documentId}`}>Document</Link></>}</div></article>)}
 <h2>Meetings, roster observations and related records ({data.occurrences.length})</h2>{data.occurrences.map((row:any)=><article className="card" key={row._id} style={{marginBottom:8}}><div className="card__body"><strong>{row.observedDate||'Date unknown'} · {row.context} · {row.personName}</strong><p>Identity: {row.matchStatus} · Source role: {sourceRoleLabel(row.roleTitle)} · Source affiliation: {row.affiliation||'Unknown'}</p>{row.notes&&<p>{row.notes}</p>}{row.historical&&<p>Verified history at this meeting: role {row.historical.role.state}; affiliation {row.historical.affiliation.state}</p>}<Link to={row.href}>Open related record</Link> · <a href={row.sourceUrl} target="_blank" rel="noreferrer">Source</a> · {row.sourceReference}</div></article>)}
 </div>;
}
