import {sourceRoleLabel} from '../../shared/personHistory';
import {useMemo,useState} from 'react';import {Link,useParams} from 'react-router-dom';import {useMutation,useQuery} from 'convex/react';import {api} from '@/lib/convexApi';import {useSociety} from '@/hooks/useSociety';import {usePermissions} from '@/hooks/usePermissions';import {useToast} from '@/components/Toast';import {PageLoading,SeedPrompt} from './_helpers';import {PersonOccurrenceReview} from '@/components/PersonRecordLinks';
import {useConfirm} from '@/components/Modal';import {EmptyState} from '@/components/ui';import {UnsupportedDetailsBadge} from '@/components/UnsupportedDetailsBadge';import {PersonPicker,useDirectoryPeople} from '@/components/PersonPicker';import {PersonMergeDialog} from '../features/people/PersonMergeDialog';
import {GitMerge,UserX,Undo2,Wrench} from 'lucide-react';import {useRecordQuery} from '@/hooks/useRecordQuery';

const PAGE=25;
function Pager({page,count,setPage,label}:{page:number;count:number;setPage:(n:number)=>void;label:string}){
 const pages=Math.max(1,Math.ceil(count/PAGE));if(pages<2)return null;
 return <nav className="row" aria-label={`${label} pages`} style={{gap:12,margin:'8px 0',alignItems:'center',flexWrap:'wrap'}}><button className="btn btn--sm" disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span className="muted">Page {page+1} of {pages}</span><button className="btn btn--sm" disabled={page+1>=pages} onClick={()=>setPage(page+1)}>Next</button></nav>;
}

/** P8: find and move history entries left behind by earlier re-links. */
function RepairLostHistory({societyId}:{societyId:string}){
 const repair=useMutation(api.personHistory.repairOrphanedEvents);const confirm=useConfirm();const toast=useToast();const [busy,setBusy]=useState(false);
 return <button className="btn btn--sm" disabled={busy} onClick={async()=>{setBusy(true);try{
  const preview:any=await repair({societyId,dryRun:true});
  if(!preview.count){toast.info('No lost history found','Every history entry is on the same person as its source occurrence.');return;}
  const ok=await confirm({title:`Move ${preview.count} history entr${preview.count===1?'y':'ies'}?`,message:<><p style={{margin:'0 0 8px'}}>Earlier re-links moved these source occurrences to another person but left their history behind, so it was hidden on both profiles. They will move to the person the occurrence is linked to now.</p><ul style={{margin:0,paddingLeft:18}}>{preview.examples.slice(0,8).map((e:any)=><li key={e.id}>{e.title??e.table}</li>)}</ul></>,confirmLabel:'Move history'});
  if(!ok)return;const result:any=await repair({societyId,dryRun:false});toast.success('History repaired',`${result.count} entries moved`);
 }catch(e:any){toast.error('Repair failed',e.message);}finally{setBusy(false);}}}><Wrench size={12}/> Find history lost by earlier re-links</button>;
}

export function PersonReviewPage(){
 const society=useSociety();const {can}=usePermissions();const data=useQuery(api.personHistory.overview,society&&can('members:read')?{societyId:society._id}:'skip') as any;
 const [search,setSearch]=useState('');const [status,setStatus]=useState('pending');const [page,setPage]=useState(0);const [name,setName]=useState('');const toast=useToast();const create=useMutation(api.personHistory.createContact);
 const matches=useMemo(()=>{if(!data)return [];const query=search.toLocaleLowerCase();return data.occurrences.filter((r:any)=>(status==='all'||(status==='pending'?['suggested','unresolved','assumed'].includes(r.matchStatus):status==='ambiguous'?(r.candidates?.length??0)>1&&r.matchStatus!=='verified':status==='named_fragment'?r.matchStatus==='not_person'&&(r.namedPeople?.length??0)>0:r.matchStatus===status))&&[r.personName,r.context,r.affiliation,r.notes].join(' ').toLocaleLowerCase().includes(query));},[data,search,status]);
 if(society===undefined)return <PageLoading/>;if(!society)return <SeedPrompt/>;if(!can('members:read'))return <p>People access required.</p>;if(!data)return <PageLoading/>;
 const query=search.toLocaleLowerCase();
 return <div className="page"><h1>People, source identities and history</h1><p>Contact profiles connect meeting attendance, notes, roles and affiliations. Test assumptions connect the interface while retaining an unconfirmed identity label; membership and voting rights are assessed separately.</p>
 <p>{data.people.length} contact profiles · {data.occurrences.length} source occurrences · {data.occurrences.filter((r:any)=>r.matchStatus==='verified').length} confirmed identity links · {data.occurrences.filter((r:any)=>r.matchStatus==='assumed').length} test assumptions</p>
 <div className="row" style={{gap:8,flexWrap:'wrap'}}><input className="input" aria-label="Search people and evidence" placeholder="Search names, affiliations or notes" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/><select className="input" aria-label="Identity review filter" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}>{[['pending','Pending identity review'],['ambiguous','Ambiguous names (several possible people)'],['all','All occurrences'],['verified','Confirmed'],['assumed','Test assumptions'],['not_person','Organizations and headings'],['named_fragment','Headings that contain a known name'],['rejected','Rejected']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{can('members:write')&&<RepairLostHistory societyId={society._id}/>}<Link className="btn btn--sm" to="/app/people-directory">Duplicates and merges</Link></div>
 <details style={{margin:'16px 0'}}><summary>Person profiles ({data.people.length})</summary><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:8,marginTop:12}}>{data.people.filter((p:any)=>[p.fullName,...(p.aliases??[])].join(' ').toLocaleLowerCase().includes(query)).map((p:any)=><Link key={p._id} to={`/app/people-directory/${p._id}`}>{p.fullName} · {p.occurrences} observations · {p.unreviewed} unreviewed</Link>)}</div></details>
 {can('members:write')&&<details><summary>Create a contact profile</summary><label>Person's name<input className="input" value={name} onChange={e=>setName(e.target.value)}/></label><button className="btn" disabled={!name.trim()} onClick={async()=>{try{await create({societyId:society._id,fullName:name});setName('');toast.success('Contact profile created');}catch(e:any){toast.error(e.message);}}}>Create contact</button></details>}
 <h2>Source identity review ({matches.length})</h2>{matches.slice(page*30,page*30+30).map((row:any)=><PersonOccurrenceReview key={row._id+row.matchStatus+(row.personId??'')} row={row} people={data.people}/>)}<div className="row" style={{gap:12,marginTop:12}}><button className="btn" disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(matches.length/30))}</span><button className="btn" disabled={(page+1)*30>=matches.length} onClick={()=>setPage(page+1)}>Next</button></div>
 </div>;
}

/** P17: one card per fact. Events with the same kind, value and date from several sources collapse into one. */
function groupEvents(events:any[]){
 const groups=new Map<string,any[]>();
 for(const ev of events){const key=[ev.kind,(ev.value||ev.roleTitle||ev.title||'').toLocaleLowerCase().replace(/\s+/g,' ').trim(),(ev.affiliation||'').toLocaleLowerCase(),ev.effectiveDate,ev.endDate??''].join('|');groups.set(key,[...(groups.get(key)??[]),ev]);}
 return [...groups.values()].map(list=>({primary:list.find(e=>e.reviewStatus==='verified')??list[0],others:list}));
}

function EventReviewForm({societyId,eventId}:{societyId:string;eventId:string}){
 const reviewEvent=useMutation(api.personHistory.reviewEvent);const toast=useToast();const [status,setStatus]=useState('');const [rationale,setRationale]=useState('');
 return <form className="col event-review-form" style={{gap:8,marginTop:8}} onSubmit={async e=>{e.preventDefault();try{await reviewEvent({societyId,eventId,status,rationale});toast.success('History evidence review recorded');setRationale('');}catch(error:any){toast.error(error.message);}}}>
  <label style={{display:'block'}}>Review outcome<select className="input" value={status} required onChange={e=>setStatus(e.target.value)}><option value="" disabled>Choose an outcome</option><option value="pending">Pending</option><option value="verified">Verified against source</option><option value="rejected">Rejected</option></select></label>
  <label style={{display:'block'}}>Review rationale<input className="input" value={rationale} required onChange={e=>setRationale(e.target.value)} placeholder="What you checked in the source"/></label>
  <button className="btn" type="submit" disabled={!status||!rationale.trim()}>Record review</button></form>;
}

function MergeIntoThis({societyId,person}:{societyId:string;person:any}){
 const people=useDirectoryPeople(societyId);const [otherId,setOtherId]=useState('');const [open,setOpen]=useState(false);
 const other=people?.find(p=>p._id===otherId);
 return <div className="row" style={{gap:8,flexWrap:'wrap',alignItems:'center'}}>
  <PersonPicker people={people?.filter(p=>p._id!==person._id)} value={otherId} onChange={setOtherId} sourceName={person.fullName} placeholder="Another profile for the same person" ariaLabel="Profile to merge into this one" style={{minWidth:240}}/>
  <button className="btn btn--sm" disabled={!other} onClick={()=>setOpen(true)}><GitMerge size={12}/> Merge…</button>
  {open&&other&&<PersonMergeDialog societyId={societyId} people={[{id:person._id,fullName:person.fullName},{id:other._id,fullName:other.fullName}]} onClose={()=>{setOpen(false);setOtherId('');}}/>}
 </div>;
}

export function PersonProfilePage(){
 const {id}=useParams();const society=useSociety();const {can}=usePermissions();const toast=useToast();const confirm=useConfirm();const [asOf,setAsOf]=useState('');
 // P12: a profile from another workspace (or a missing id) resolves to null and shows a not-found state.
 const data=useRecordQuery<any>(api.personHistory.profile,society&&id&&can('members:read')?{societyId:society._id,personId:id,...(asOf?{asOf}:{})}:'skip');
 const merges=useQuery(api.personHistory.mergeHistory,society&&id&&can('members:read')?{societyId:society._id,personId:id}:'skip') as any[]|undefined;
 const unmerge=useMutation(api.personHistory.unmergePeople);
 const addContact=useMutation(api.personHistory.addContactPoint);const [contact,setContact]=useState({kind:'email',value:'',observedDate:'',reviewStatus:'pending',sourceUrl:'',sourceReference:''});
 const add=useMutation(api.personHistory.addEvent);const aliases=useMutation(api.personHistory.setAliases);const [alias,setAlias]=useState('');const [aliasSource,setAliasSource]=useState('');const [aliasCitation,setAliasCitation]=useState('');
 const blank={kind:'observation',title:'',value:'',scope:'general',effectiveDate:'',endDate:'',transition:'observed',details:'',reviewStatus:'pending',sourceUrl:'',sourceReference:'',supersedesEventId:''};const [form,setForm]=useState(blank);const [busy,setBusy]=useState(false);
 const [eventPage,setEventPage]=useState(0);const [occPage,setOccPage]=useState(0);
 const grouped=useMemo(()=>groupEvents(data?.events??[]),[data]);
 if(society===undefined)return <PageLoading/>;if(!society)return <SeedPrompt/>;if(!can('members:read'))return <p>People access required.</p>;if(data===undefined)return <PageLoading/>;
 if(data===null||data.notFound)return <div className="page"><EmptyState icon={<UserX size={18}/>} title="Person not found in this workspace" description="This profile does not exist here. It may belong to another workspace, or the link is out of date." action={<Link className="btn btn--accent" to="/app/people-directory">Back to the people directory</Link>}/></div>;
 if(data.mergedInto)return <div className="page"><EmptyState icon={<GitMerge size={18}/>} title={`${data.person.fullName} was merged`} description={`This profile was merged into ${data.mergedInto.fullName}. Its history now appears there.`} action={<Link className="btn btn--accent" to={`/app/people-directory/${data.mergedInto._id}`}>Open {data.mergedInto.fullName}</Link>}/></div>;
 const field=(key:keyof typeof blank,label:string)=><label style={{display:'block'}}>{label}<input className="input" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 const occurrences:any[]=data.occurrences;
 return <div className="page person-profile"><Link to="/app/people-history">All people and identity reviews</Link>
 <div className="row" style={{gap:10,alignItems:'center',flexWrap:'wrap'}}><h1 style={{margin:'8px 0'}}>{data.person.fullName}</h1><UnsupportedDetailsBadge table="peopleDirectory" id={data.person._id}/></div>
 <p>Aliases: {(data.person.aliases??[]).join(', ')||'None confirmed'}</p><p>Source observations retain their wording and dates. Pending links and test assumptions are displayed for review. Contact identity alone does not establish membership or voting eligibility.</p>
 <nav className="row" aria-label="Sections" style={{gap:12,flexWrap:'wrap',fontSize:'var(--fs-sm)'}}><a href="#history">Dated history ({data.events.length})</a><a href="#occurrences">Meetings and roster observations ({occurrences.length})</a>{!!data.contactPoints?.length&&<a href="#contacts">Contact details</a>}</nav>
 {can('members:write')&&<section className="card" style={{marginTop:12}}><div className="card__body col" style={{gap:8}}><h2 style={{margin:0}}>Same person under another profile?</h2><p className="muted" style={{margin:0}}>Merging moves the other profile's history, attendance, motions, tasks and register links here, keeps its name as an alias, and can be undone.</p><MergeIntoThis societyId={society._id} person={data.person}/>
  {!!merges?.length&&<ul style={{margin:0,paddingLeft:18}}>{merges.map(m=><li key={m._id}>{m.createdAtISO.slice(0,10)} · {m.mergedName} {m.survivorId===data.person._id?'merged into this profile':`→ ${m.survivorName}`} · {m.movedReferences} links · {m.status==='undone'?'undone':<button className="btn btn--ghost btn--sm" onClick={async()=>{const ok=await confirm({title:`Undo merge of ${m.mergedName}?`,message:`${m.mergedName} becomes a separate profile again and the moved links go back.`,confirmLabel:'Undo merge',tone:'warn'});if(!ok)return;try{await unmerge({societyId:society._id,mergeId:m._id});toast.success('Merge undone');}catch(e:any){toast.error(e.message);}}}><Undo2 size={12}/> Undo</button>}</li>)}</ul>}
 </div></section>}
 <section className="card" style={{marginTop:16}}><div className="card__body"><h2>Historical role and affiliation</h2><label>As of meeting day<input className="input" aria-label="Historical day" type="date" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label>{data.historical&&['role','affiliation'].map(kind=><p key={kind}>{kind}: <strong>{data.historical[kind].state}</strong> · {data.historical[kind].values.map((v:any)=>`${v.value} (${v.scope})`).join('; ')||'No verified effective interval'}</p>)}<p className="muted">A roster observation applies to its source period. It is not carried back or forward as a confirmed appointment. Changes with month or year precision remain uncertain inside that period.</p></div></section>
 {can('members:write')&&<details className="card" style={{marginTop:16}}><summary className="card__body">Record a dated change or contextual note</summary><div className="card__body col" style={{gap:10}}>
 <label style={{display:'block'}}>Kind<select className="input" aria-label="Kind" value={form.kind} onChange={e=>setForm({...form,kind:e.target.value,transition:['role','affiliation'].includes(e.target.value)?'changed':'observed'})}>{['observation','role','affiliation','appointment','departure','note'].map(k=><option key={k}>{k}</option>)}</select></label>
 {field('title','Title')}{field('value','New role or affiliation value')}{field('scope','Organization, committee or role scope')}{field('effectiveDate','Effective source date (YYYY, YYYY-MM or YYYY-MM-DD)')}{field('endDate','End date, if established')}
 <label style={{display:'block'}}>Change type<select className="input" value={form.transition} onChange={e=>setForm({...form,transition:e.target.value})}>{['observed','started','changed','ended'].map(k=><option key={k}>{k}</option>)}</select></label>
 <label style={{display:'block'}}>Previous event retained in history<select className="input" value={form.supersedesEventId} onChange={e=>setForm({...form,supersedesEventId:e.target.value})}><option value="">No established previous event</option>{data.events.filter((ev:any)=>ev.kind===form.kind&&ev.scope===form.scope).map((ev:any)=><option key={ev._id} value={ev._id}>{ev.effectiveDate} · {ev.title} · {ev.reviewStatus}</option>)}</select></label>
 <label style={{display:'block'}}>Context / note<textarea className="input" value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></label>{field('sourceUrl','Source URL')}{field('sourceReference','Page, section or cell citation')}
 <label style={{display:'block'}}>Source review<select className="input" value={form.reviewStatus} onChange={e=>setForm({...form,reviewStatus:e.target.value})}>{['pending','verified','rejected'].map(k=><option key={k}>{k}</option>)}</select></label>
 <button className="btn" disabled={busy||!form.title||!form.effectiveDate||!form.sourceReference||!form.sourceUrl} onClick={async()=>{setBusy(true);try{const event:any={...form,eventKey:crypto.randomUUID()};if(!event.endDate)delete event.endDate;if(!event.supersedesEventId)delete event.supersedesEventId;await add({societyId:society._id,personId:id,event});setForm(blank);toast.success('Dated history recorded; earlier evidence retained');}catch(e:any){toast.error(e.message);}finally{setBusy(false);}}}>Save dated event</button>
 </div></details>}
 {can('members:write')&&<details className="card" style={{marginTop:16}}><summary className="card__body">Confirm a name alias</summary><div className="card__body col" style={{gap:8}}><label style={{display:'block'}}>Alias<input className="input" value={alias} onChange={e=>setAlias(e.target.value)}/></label><label style={{display:'block'}}>Source URL<input className="input" value={aliasSource} onChange={e=>setAliasSource(e.target.value)}/></label><label style={{display:'block'}}>Citation<input className="input" value={aliasCitation} onChange={e=>setAliasCitation(e.target.value)}/></label><button className="btn" disabled={!alias||!aliasSource||!aliasCitation} onClick={async()=>{try{await aliases({societyId:society._id,personId:id,aliases:[alias],source:{sourceUrl:aliasSource,sourceReference:aliasCitation,reviewStatus:'verified'}});setAlias('');toast.success('Alias evidence recorded');}catch(e:any){toast.error(e.message);}}}>Add reviewed alias</button></div></details>}
 {!!data.registers?.length&&<section className="card" style={{marginTop:16}}><div className="card__body"><h2>Linked membership and director records</h2>{data.registers.map((r:any)=><div key={r._id}><Link to={r.href}>{r.recordTable==='members'?'Member record':'Director register'}: {r.firstName} {r.lastName}</Link><p>{r.position||r.membershipClass} · {r.status} · {r.termStart||r.joinedAt}{r.termEnd||r.leftAt?` to ${r.termEnd||r.leftAt}`:''}</p>{r.notes&&<p>{r.notes}</p>}</div>)}</div></section>}
 {can('members:write')&&<details className="card" style={{marginTop:16}}><summary className="card__body">Record a dated contact detail</summary><form className="card__body col" style={{gap:8}} onSubmit={async e=>{e.preventDefault();try{await addContact({societyId:society._id,personId:id,point:{...contact,pointKey:crypto.randomUUID()}});setContact({...contact,value:''});toast.success('Dated contact observation saved');}catch(error:any){toast.error(error.message);}}}><label style={{display:'block'}}>Contact type<select className="input" value={contact.kind} onChange={e=>setContact({...contact,kind:e.target.value})}>{['email','phone','address','other'].map(k=><option key={k}>{k}</option>)}</select></label>{[['value','Contact value'],['observedDate','Observed source date'],['sourceUrl','Contact source URL'],['sourceReference','Contact source citation']].map(([k,l])=><label style={{display:'block'}} key={k}>{l}<input className="input" required value={(contact as any)[k]} onChange={e=>setContact({...contact,[k]:e.target.value})}/></label>)}<label style={{display:'block'}}>Contact review<select className="input" value={contact.reviewStatus} onChange={e=>setContact({...contact,reviewStatus:e.target.value})}><option>pending</option><option>verified</option></select></label><button className="btn" type="submit">Save contact observation</button></form></details>}
 {!!data.contactPoints?.length&&<section id="contacts" className="card" style={{marginTop:16}}><div className="card__body"><h2>Contact details observed in sources</h2><p>These values retain their source periods; current contact details require confirmation.</p>{data.contactPoints.map((c:any)=><p key={c._id}>{c.observedDate} · {c.kind}: {c.value} · {c.reviewStatus}{c.testOnlyAssumption?' · Test identity assumption':''} · <a href={c.sourceUrl} target="_blank" rel="noreferrer">{c.sourceReference}</a></p>)}</div></section>}
 <h2 id="history">Dated history and contextual notes ({data.events.length}{grouped.length!==data.events.length?`, ${grouped.length} distinct`:''})</h2>
 <Pager page={eventPage} count={grouped.length} setPage={setEventPage} label="History"/>
 {grouped.slice(eventPage*PAGE,eventPage*PAGE+PAGE).map(({primary:ev,others}:any)=><article className="card" key={ev._id} style={{marginBottom:8}}><div className="card__body"><strong>{ev.effectiveDate}{ev.endDate?` to ${ev.endDate}`:''} · {ev.title}</strong><p>{ev.kind} · {ev.scope} · {ev.transition} · {ev.reviewStatus}{ev.testOnlyAssumption?' · Test identity assumption':''}{ev.value?` · ${ev.value}`:''}</p>{ev.details&&<p>{ev.details}</p>}{ev.supersedesEventId&&<p>Previous event retained: {data.events.find((x:any)=>x._id===ev.supersedesEventId)?.title||ev.supersedesEventId}</p>}{ev.sourceUrl&&<a href={ev.sourceUrl} target="_blank" rel="noreferrer">Source</a>} · {ev.sourceReference}{ev.href&&<> · <Link to={ev.href}>Linked member history</Link></>}{ev.meetingId&&<> · <Link to={`/app/meetings/${ev.meetingId}?tab=minutes`}>Meeting</Link></>}{ev.documentId&&<> · <Link to={`/app/documents/${ev.documentId}`}>Document</Link></>}
  {others.length>1&&<details style={{marginTop:6}}><summary>Also recorded in {others.length-1} other source{others.length===2?'':'s'}</summary>{others.filter((o:any)=>o._id!==ev._id).map((o:any)=><p key={o._id} style={{margin:'4px 0'}}>{o.title} · {o.reviewStatus} · {o.sourceUrl?<a href={o.sourceUrl} target="_blank" rel="noreferrer">{o.sourceReference}</a>:o.sourceReference}</p>)}</details>}
  {can('members:write')&&!ev.derived&&<details style={{marginTop:8}}><summary>Review this history evidence</summary><EventReviewForm societyId={society._id} eventId={ev._id}/></details>}</div></article>)}
 <Pager page={eventPage} count={grouped.length} setPage={setEventPage} label="History"/>
 <h2 id="occurrences">Meetings, roster observations and related records ({occurrences.length})</h2>
 <Pager page={occPage} count={occurrences.length} setPage={setOccPage} label="Observations"/>
 {occurrences.slice(occPage*PAGE,occPage*PAGE+PAGE).map((row:any)=><article className="card" key={row._id} style={{marginBottom:8}}><div className="card__body"><strong>{row.observedDate||'Date unknown'} · {row.context} · {row.personName}</strong><p>Identity: {row.matchStatus==='assumed'?'Test assumption — identity unconfirmed':row.matchStatus} · Source role: {sourceRoleLabel(row.roleTitle)} · Source affiliation: {row.affiliation||'Unknown'}</p>{row.notes&&<p>{row.notes}</p>}{row.historical&&<p>Verified history at this meeting: role {row.historical.role.state}; affiliation {row.historical.affiliation.state}</p>}<Link to={row.href}>Open related record</Link> · <a href={row.sourceUrl} target="_blank" rel="noreferrer">Source</a> · {row.sourceReference}</div></article>)}
 <Pager page={occPage} count={occurrences.length} setPage={setOccPage} label="Observations"/>
 </div>;
}
