import {useState} from 'react';import {Link} from 'react-router-dom';import {useQuery} from 'convex/react';import {api} from '@/lib/convexApi';import {useSociety} from '@/hooks/useSociety';import {usePermissions} from '@/hooks/usePermissions';import {PageLoading,SeedPrompt} from './_helpers';
const destinations:Record<string,{name:string;href:string;fields:string;unknown:string}>={
 peopleDirectory:{name:'People, roles and affiliations',href:'/app/people-history',fields:'Source names, contact profiles, identity suggestions, roster observations, meeting context and dated history',unknown:'Confirmed identity, legal membership, voting rights and current appointment intervals'},
 minutes:{name:'Meetings and minutes',href:'/app/meetings',fields:'Draft wording, source dates, attendance fragments, decisions, quorum checkpoints and future suggestions',unknown:'Original column alignment, exact meeting time, adoption and historical voting eligibility'},
 committees:{name:'Committees and mandates',href:'/app/committees',fields:'Names observed in the roster, source notes and committee/role observations',unknown:'Current mandate, active status, chair, cadence and appointment dates'},
 financialStatementImports:{name:'Financial statements and budgets',href:'/app/financials/accounting',fields:'Separate statement versions, comparative source rows, program actuals and budgets',unknown:'Verified current version, currency, opening balances and complete posted ledger'},
 transactionCandidates:{name:'Payments and bank reconciliation',href:'/app/financials/accounting',fields:'Linked bank, invoice, receipt and payment source evidence',unknown:'Verified postings, payment allocations and unresolved reconciliation differences'},
 insurancePolicies:{name:'Insurance',href:'/app/insurance',fields:'Historical policy terms, insurer/broker, premiums, fees, locations and source evidence',unknown:'Current coverage, unsourced limits, combined-payment allocations and unmet renewal requirements'},
 documents:{name:'Policies, agreements and other records',href:'/app/documents',fields:'Source documents, citations, original hashes, text and source history',unknown:'Adopted policy version, operative agreement, signatures and ownership of ambiguous records'},
 commitments:{name:'Programs, projects and commitments',href:'/app/commitments',fields:'Source material mapped for program and commitment review',unknown:'Confirmed current commitments, owners, effective dates and completion'},
 grantApplications:{name:'Funding and grants',href:'/app/grants',fields:'Source funding, proposal and contribution material mapped for review',unknown:'Verified grant awards, conditions, amounts and reporting obligations'},
 communicationCampaigns:{name:'Communications and outreach',href:'/app/communications',fields:'Source newsletters, posters, outreach and communication material',unknown:'Approved current recipients, consent, campaign status and publication authority'},
 assets:{name:'Assets and equipment',href:'/app/assets',fields:'Source inventory, equipment and monitoring material mapped for review',unknown:'Current ownership, asset identity, value, condition and custody'},
};
export function SourceModelCoveragePage(){
 const society=useSociety();const {can}=usePermissions();const data=useQuery(api.evidenceRegisters.overview,society&&can('documents:read')?{societyId:society._id}:'skip') as any;
 const people=useQuery(api.personHistory.overview,society&&can('members:read')?{societyId:society._id}:'skip') as any;
 const [destination,setDestination]=useState('all');const [search,setSearch]=useState('');const [page,setPage]=useState(0);
 if(society===undefined)return <PageLoading/>;if(!society)return <SeedPrompt/>;if(!can('documents:read'))return <p>Source-document access required.</p>;if(!data)return <PageLoading/>;
 const sources=data.sourceEvidence.filter((s:any)=>s._id.startsWith('pgair_model_source_'));const filtered=sources.filter((s:any)=>(destination==='all'||s.targetTable===destination)&&[s.sourceTitle,s.summary,s.notes].join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 return <div className="page"><h1>Source coverage across the Societyer model</h1><p>Evidence is populated as source drafts and review observations. A file assigned to a model area remains evidence for review until its fields are established from the source.</p>
 <div className="stat-grid"><div className="stat"><div className="stat__label">Readable source files indexed</div><div className="stat__value">{sources.length}</div></div><div className="stat"><div className="stat__label">Contact profiles</div><div className="stat__value">{people?.people.length??'Access limited'}</div></div><div className="stat"><div className="stat__label">Attendance evidence</div><div className="stat__value">{data.meetingAttendanceRecords.length}</div></div><div className="stat"><div className="stat__label">Statement / budget versions</div><div className="stat__value">{data.financialStatementImports.length} / {data.budgetSnapshots.length}</div></div></div>
 <div style={{overflowX:'auto',margin:'16px 0'}}><table className="table"><thead><tr><th>Model area</th><th>Populated evidence and fields</th><th>Fields still requiring evidence</th><th>Primary source files</th></tr></thead><tbody>{Object.entries(destinations).map(([table,d])=><tr key={table}><td><Link to={d.href}>{d.name}</Link></td><td>{d.fields}</td><td>{d.unknown}</td><td><button className="btn" onClick={()=>{setDestination(table);setPage(0);}}>{sources.filter((s:any)=>s.targetTable===table).length}</button></td></tr>)}</tbody></table></div>
 <p>Use <Link to="/app/tasks">historical action review tasks</Link> to assess source action wording and completion. <Link to="/app/people-history">Review person identities</Link> before confirming source-derived person history. Unread files, OCR uncertainty and original verification remain recorded in the exported review report.</p>
 <h2>Source files and model destinations</h2><div className="row" style={{gap:8,flexWrap:'wrap'}}><label>Destination<select className="input" aria-label="Destination" value={destination} onChange={e=>{setDestination(e.target.value);setPage(0);}}><option value="all">All source destinations</option>{Object.entries(destinations).map(([t,d])=><option key={t} value={t}>{d.name}</option>)}</select></label><label>Search source files<input className="input" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label></div>
 {filtered.slice(page*25,page*25+25).map((s:any)=><article key={s._id} className="card" style={{marginTop:8}}><div className="card__body"><h3>{s.sourceTitle}</h3><p>{s.summary}</p><p>{s.status} · {destinations[s.targetTable]?.name??s.targetTable}</p>{s.sourceDocumentId&&<Link to={`/app/documents/${s.sourceDocumentId}`}>Open source document and evidence</Link>}{s.externalId?.startsWith('google-drive:')&&<> · <a href={`https://drive.google.com/file/d/${s.externalId.slice(13)}/view`} target="_blank" rel="noreferrer">Original on Drive</a></>}<details><summary>Extracted source preview</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{s.excerpt}</pre><p>{s.notes}</p></details></div></article>)}
 <div className="row" style={{gap:12,marginTop:12}}><button className="btn" disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(filtered.length/25))} · {filtered.length} files</span><button className="btn" disabled={(page+1)*25>=filtered.length} onClick={()=>setPage(page+1)}>Next</button></div>
 </div>;
}
