// WorkflowDetail: node setup panel orchestrator plus document/email defaults and document-create config.
import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useAction, useMutation, useQuery } from "convex/react";
import {
  Background,
  Controls,
  Handle,
  Position,
  ReactFlow,
  type Edge,
  type Node,
  type NodeProps,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { api } from "@/lib/convexApi";
import { useSociety } from "../hooks/useSociety";
import { useCurrentUserId } from "../hooks/useCurrentUser";
import { useToast } from "../components/Toast";
import { Badge, Drawer, Field } from "../components/ui";
import { MarkdownEditor } from "../components/MarkdownEditor";
import { Modal } from "../components/Modal";
import { SeedPrompt } from "./_helpers";
import {
  ArrowLeft,
  Bot,
  ClipboardList,
  ExternalLink,
  FileText,
  FormInput,
  History,
  Mail,
  Pause,
  Play,
  Plus,
  Power,
  Save,
  Settings,
  Trash2,
  UserPlus,
} from "lucide-react";
import { formatDateTime } from "../lib/format";
import {
  FIELD_LABELS,
  TemplateToken,
  configuredIntakeFields,
  normalizeIntakeFields,
} from "./WorkflowDetail.internal.intakeFields";
import {
  LabeledInput,
  LabeledTextarea,
  TemplateTextarea,
} from "./WorkflowDetail.internal.fieldInputs";
import {
  IntakeFieldSetup,
} from "./WorkflowDetail.internal.intakeWizard";
import {
  PdfFillSetup,
} from "./WorkflowDetail.internal.pdfFill";


export function documentDefaults(workflow: any) {
  const cfg = workflow?.config ?? {};
  if (cfg.pdfTemplateKey !== "unbc_affiliate_id") return {};
  return {
    category: cfg.documentCategory ?? "WorkflowGenerated",
    tags: Array.isArray(cfg.documentTags) ? cfg.documentTags : ["workflow-generated", "unbc-affiliate-id"],
    retentionYears: typeof cfg.documentRetentionYears === "number" ? cfg.documentRetentionYears : 10,
    titleTemplate:
      cfg.documentTitleTemplate ??
      "UNBC Affiliate ID Request - {{intake.legal_first_name_of_affiliate}} {{intake.legal_last_name_of_affiliate}}",
    changeNote: cfg.documentChangeNote ?? "Generated by UNBC Affiliate ID Request workflow.",
  };
}

export function emailDefaults(workflow: any) {
  const cfg = workflow?.config ?? {};
  if (cfg.pdfTemplateKey !== "unbc_affiliate_id") return {};
  return {
    to: cfg.emailTo ?? "employmentprocessing@unbc.ca",
    subject:
      cfg.emailSubject ??
      "Completed affiliate status request form - {{intake.legal_first_name_of_affiliate}} {{intake.legal_last_name_of_affiliate}}",
    body:
      cfg.emailBody ??
      [
        "Hello,",
        "",
        "Please see the attached completed UNBC affiliate status request form for {{intake.legal_first_name_of_affiliate}} {{intake.legal_last_name_of_affiliate}}.",
        "",
        "The generated PDF is attached for processing.",
        "",
        "Thanks,",
        "{{intake.name_of_requesting_manager}}",
      ].join("\n"),
  };
}

export function workflowTemplateTokens(workflow: any): TemplateToken[] {
  const intakeTokens = configuredIntakeFields(workflow).map((field) => ({
    group: "Intake",
    label: field.label,
    value: `{{intake.${field.key}}}`,
  }));
  return [
    ...intakeTokens,
    { group: "Document", label: "Generated PDF title", value: "{{document.title}}" },
    { group: "Document", label: "Generated PDF file name", value: "{{document.fileName}}" },
    { group: "Document", label: "Document category", value: "{{document.category}}" },
    { group: "Workflow", label: "Workflow name", value: "{{workflow.name}}" },
    { group: "Workflow", label: "Run ID", value: "{{run.id}}" },
    { group: "User", label: "Launcher name", value: "{{currentUser.name}}" },
    { group: "User", label: "Launcher email", value: "{{currentUser.email}}" },
    { group: "Dynamic", label: "Today", value: "{{today}}" },
  ];
}

export type NodeSetupPanelProps = {
  node: any;
  workflow: any;
  documents: any[];
  onLaunch: () => void;
  launchDisabled?: boolean;
  onSave: (patch: Record<string, any>) => Promise<void>;
};

export function NodeSetupPanel({ node, workflow, documents, onLaunch, launchDisabled, onSave }: NodeSetupPanelProps) {
  const cfg = node.config ?? {};
  const recipeCfg = workflow?.config ?? {};
  const emailCfg = { ...emailDefaults(workflow), ...cfg };

  const blurbs: Record<string, string> = {
    manual_trigger: "A person starts this workflow from inside Societyer. No external setup required.",
    form: "Collects structured input before handing off to later steps. Define the fields to collect.",
    pdf_fill: "Picks up a fillable PDF from Documents, fills mapped AcroForm fields, and saves the output as a new document version.",
    document_create: "Saves the output of a prior step into Documents with a category and retention policy.",
    email: "Queues a manual-send Outbox draft with templated content and the generated document attached.",
    ai_agent: "Runs a permissioned Societyer AI agent. The prompt can include workflow and intake variables.",
    external_n8n: "Hands execution to an n8n workflow via its webhook URL. n8n then calls back to progress the timeline.",
  };
  const launchLabel =
    typeof cfg.launchLabel === "string" && cfg.launchLabel.trim()
      ? cfg.launchLabel.trim()
      : "Launch workflow";

  return (
    <div className="workflow-sidepanel__section workflow-setup">
      <div className="field__label">Setup</div>
      <p className="muted" style={{ fontSize: "var(--fs-sm)", marginBottom: 8 }}>
        {blurbs[node.type] ?? "No setup options for this node type."}
      </p>

      {node.type === "manual_trigger" && (
        <>
          <button
            type="button"
            className="btn btn--accent btn--sm"
            disabled={launchDisabled}
            onClick={onLaunch}
          >
            <Play size={12} /> {launchLabel}
          </button>
          <LabeledInput
            label="Trigger label"
            value={cfg.launchLabel ?? ""}
            placeholder="Launch workflow"
            onSave={(v) => onSave({ launchLabel: v })}
          />
        </>
      )}

      {node.type === "form" && (
        <IntakeFieldSetup
          fields={normalizeIntakeFields(
            cfg.fields,
            recipeCfg.intakeFields ??
              recipeCfg.pdfFields ??
              (recipeCfg.sampleAffiliate && typeof recipeCfg.sampleAffiliate === "object"
                ? Object.keys(recipeCfg.sampleAffiliate)
                : FIELD_LABELS),
          )}
          onSave={(fields) => onSave({ fields })}
        />
      )}

      {node.type === "pdf_fill" && (
        <PdfFillSetup
          node={node}
          cfg={cfg}
          intakeFields={configuredIntakeFields(workflow)}
          documents={documents}
          recipeFields={Array.isArray(recipeCfg.pdfFields) ? recipeCfg.pdfFields : []}
          onSave={onSave}
        />
      )}

      {node.type === "document_create" && (
        <DocumentCreateSetup
          cfg={cfg}
          defaults={documentDefaults(workflow)}
          onSave={onSave}
        />
      )}

      {node.type === "email" && (
        <>
          <LabeledInput
            label="To"
            value={emailCfg.to ?? ""}
            placeholder="recipient@example.com"
            onSave={(v) => onSave({ to: v })}
          />
          <LabeledInput
            label="Subject"
            value={emailCfg.subject ?? ""}
            placeholder="Completed affiliate status request form"
            onSave={(v) => onSave({ subject: v })}
          />
          <TemplateTextarea
            label="Body"
            value={emailCfg.body ?? ""}
            placeholder={"Hello,\n\nHere is the completed affiliate status request form.\n\nThanks,"}
            tokens={workflowTemplateTokens(workflow)}
            onSave={(v) => onSave({ body: v })}
          />
        </>
      )}

      {node.type === "ai_agent" && (
        <>
          <LabeledInput
            label="Agent key"
            value={cfg.agentKey ?? "compliance_analyst"}
            placeholder="compliance_analyst"
            onSave={(v) => onSave({ agentKey: v })}
          />
          <TemplateTextarea
            label="Prompt template"
            value={cfg.promptTemplate ?? "Review {{workflow.name}} with this workflow input: {{input}}"}
            placeholder="Review {{workflow.name}} with this workflow input: {{input}}"
            tokens={workflowTemplateTokens(workflow)}
            onSave={(v) => onSave({ promptTemplate: v })}
          />
        </>
      )}

      {node.type === "external_n8n" && (
        <>
          <LabeledInput
            label="Webhook URL override"
            value={cfg.webhookUrl ?? ""}
            placeholder={workflow?.providerConfig?.externalWebhookUrl ?? "https://n8n.example.com/webhook/..."}
            onSave={(v) => onSave({ webhookUrl: v })}
          />
          <LabeledInput
            label="n8n node name"
            value={cfg.nodeName ?? ""}
            placeholder="Fill UNBC ID PDF"
            onSave={(v) => onSave({ nodeName: v })}
          />
        </>
      )}

      {node.type !== "manual_trigger" && (
        <div className="workflow-setup__footer">
          <button
            type="button"
            className="btn btn--ghost btn--sm"
            disabled
            title={node.type === "ai_agent" ? "AI agent steps run as part of the workflow." : "Test harness ships with Phase 2 — executing nodes individually."}
          >
            <Play size={12} /> Test node
          </button>
          <span className="muted" style={{ fontSize: "var(--fs-xs)" }}>
            {node.type === "ai_agent"
              ? "AI agent output is stored on the workflow run step."
              : "Runner support for user-edited nodes is staged; config saved here will wire in once execution lands."}
          </span>
        </div>
      )}
    </div>
  );
}

export function DocumentCreateSetup({
  cfg,
  defaults,
  onSave,
}: {
  cfg: Record<string, any>;
  defaults: Record<string, any>;
  onSave: (patch: Record<string, any>) => Promise<void>;
}) {
  const category = cfg.category ?? defaults.category ?? "";
  const tags = Array.isArray(cfg.tags) ? cfg.tags : Array.isArray(defaults.tags) ? defaults.tags : [];
  const retentionYears = cfg.retentionYears ?? defaults.retentionYears ?? 10;
  const titleTemplate = cfg.titleTemplate ?? defaults.titleTemplate ?? "";
  const changeNote = cfg.changeNote ?? defaults.changeNote ?? "";

  return (
    <>
      <LabeledInput
        label="Category"
        value={category}
        placeholder="WorkflowGenerated"
        onSave={(v) => onSave({ category: v })}
      />
      <LabeledInput
        label="Generated document title"
        value={titleTemplate}
        placeholder="UNBC Affiliate ID Request - {{intake.legal_first_name_of_affiliate}} {{intake.legal_last_name_of_affiliate}}"
        onSave={(v) => onSave({ titleTemplate: v })}
      />
      <LabeledInput
        label="Retention years"
        value={String(retentionYears)}
        placeholder="10"
        onSave={(v) => {
          const parsed = Number(v);
          return onSave({ retentionYears: Number.isFinite(parsed) && parsed > 0 ? parsed : undefined });
        }}
      />
      <LabeledInput
        label="Tags (comma-separated)"
        value={tags.join(", ")}
        placeholder="workflow-generated, unbc-affiliate-id"
        onSave={(v) =>
          onSave({
            tags: v
              .split(",")
              .map((t) => t.trim())
              .filter(Boolean),
          })
        }
      />
      <LabeledTextarea
        label="Version note"
        value={changeNote}
        placeholder="Generated by workflow."
        onSave={(v) => onSave({ changeNote: v })}
      />
    </>
  );
}
