import {useState} from 'react';import {useMutation,useQuery} from 'convex/react';import {api} from '@/lib/convexApi';import {usePermissions} from '@/hooks/usePermissions';import {useToast} from '@/components/Toast';import {Field} from './ui';import {money} from '@/lib/format';
export function FinancialVersionCard({societyId}:{societyId:string}){
 const {can}=usePermissions(),toast=useToast();const data=useQuery(api.financialReview.versions,{societyId});const accounts=useQuery(api.accounting.chartAccounts,{societyId});
 const review=useMutation(api.financialReview.reviewVersion),select=useMutation(api.financialReview.selectVersion),map=useMutation(api.financialReview.mapCashAccount);
 const [chosen,setChosen]=useState(''),[compare,setCompare]=useState(''),[form,setForm]=useState({currency:'',programCode:'',sourceIssuedDate:'',predecessorId:'',sourceUrl:'',sourceReference:''}),[mapping,setMapping]=useState({accountId:'',classification:'',sourceUrl:'',sourceReference:''});
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[busy,setBusy]=useState(false);const cash=useQuery(api.financialReview.cashMovements,from&&to&&from<=to?{societyId,from,to}:'skip');
 const versions=[...(data?.statements??[]).map((row:any)=>({...row,table:'financialStatementImports'})),...(data?.budgets??[]).map((row:any)=>({...row,table:'budgetSnapshots'}))];const current=versions.find(row=>row._id===chosen),other=versions.find(row=>row._id===compare);
 async function run(action:()=>Promise<any>){setBusy(true);try{await action();toast.success('Financial evidence saved');}catch(error:any){toast.error(error.message);}finally{setBusy(false);}}
 return <details className="card" style={{marginTop:16,marginBottom:16}}><summary className="card__head">Statement and budget versions; cash movements</summary><div className="card__body col" style={{gap:12}}>
 <p className="muted">Keep original and revised reports separate. Selection chooses one verified version within its period, currency and program scope. Formula caches without results remain unknown. Cash-flow totals require complete posted journals and reviewed account mappings.</p>
 <Field label="Review version"><select className="input" value={chosen} onChange={e=>{setChosen(e.target.value);const row=versions.find(item=>item._id===e.target.value);setForm({...form,currency:row?.currency??'',programCode:row?.programCode??'',sourceIssuedDate:row?.sourceIssuedDate??'',predecessorId:row?.predecessorId??''});}}><option value="">Choose a report</option>{versions.map(row=><option key={row._id} value={row._id}>{row.title} · {row.periodEnd??row.fiscalYear} · {row.status}</option>)}</select></Field>
 <Field label="Compare with"><select className="input" value={compare} onChange={e=>setCompare(e.target.value)}><option value="">Choose a second version</option>{versions.map(row=><option key={row._id} value={row._id}>{row.title} · {row.periodEnd??row.fiscalYear}</option>)}</select></Field>
 {current&&<><table className="table"><thead><tr><th>Source value</th><th>{current.title}</th>{other&&<th>{other.title}</th>}</tr></thead><tbody>{['revenueCents','expensesCents','netAssetsCents','totalIncomeCents','totalExpenseCents','netCents','endingBalanceCents'].map(key=><tr key={key}><td>{key.replace(/Cents$/,'').replace(/([A-Z])/g,' $1')}</td><td>{current[key]==null?'unknown':money(current[key])} {current.currency??'unknown currency'}</td>{other&&<td>{other[key]==null?'unknown':money(other[key])} {other.currency??'unknown currency'}</td>}</tr>)}</tbody></table>
 {Object.keys(form).map(key=><Field key={key} label={({currency:'Currency',programCode:'Program scope',sourceIssuedDate:'Source-issued date',predecessorId:'Predecessor version ID',sourceUrl:'Source URL',sourceReference:'Page / cell citation'} as any)[key]}><input className="input" value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>)}
 <button className="btn-action" disabled={!can('financials:write')||busy} onClick={()=>void run(async()=>{const {sourceUrl,sourceReference,...fields}=form;await review({societyId,table:current.table,id:current._id,...fields,predecessorId:fields.predecessorId||undefined,source:{sourceUrl,sourceReference,reviewStatus:'verified'}});})}>Verify version scope and source</button>
 <button className="btn-action" disabled={!can('financials:write')||busy||current.status!=='Verified'} onClick={()=>void run(()=>select({societyId,table:current.table,id:current._id,source:{sourceUrl:form.sourceUrl,sourceReference:form.sourceReference,reviewStatus:'verified'}}))}>Select verified version for its scope</button></>}
 {(data?.selections??[]).map((row:any)=><p key={row._id}>Selected: {versions.find(version=>version._id===row.selectedId)?.title??row.selectedId} · {row.selectionHistory.length} selections retained</p>)}
 <details><summary>Reviewed cash account mappings</summary><Field label="Ledger account"><select className="input" value={mapping.accountId} onChange={e=>setMapping({...mapping,accountId:e.target.value})}><option value="">Choose an account</option>{(accounts??[]).map((row:any)=><option key={row._id} value={row._id}>{row.code} {row.name} ({row.currency})</option>)}</select></Field><Field label="Cash-flow classification"><select className="input" value={mapping.classification} onChange={e=>setMapping({...mapping,classification:e.target.value})}><option value="">Unknown</option>{['cash','operating','investing','financing'].map(value=><option key={value}>{value}</option>)}</select></Field>{['sourceUrl','sourceReference'].map(key=><Field key={key} label={key==='sourceUrl'?'Mapping source URL':'Mapping authority clause'}><input className="input" value={(mapping as any)[key]} onChange={e=>setMapping({...mapping,[key]:e.target.value})}/></Field>)}<button className="btn-action" disabled={!can('financials:write')||busy} onClick={()=>void run(()=>map({societyId,accountId:mapping.accountId,classification:mapping.classification,source:{sourceUrl:mapping.sourceUrl,sourceReference:mapping.sourceReference,reviewStatus:'verified'}}))}>Save reviewed mapping</button></details>
 <Field label="Cash movements from"><input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Through"><input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field>
 {(cash?.blockers??[]).map((message:string)=><p className="muted" key={message}>{message}</p>)}{(cash?.rows??[]).map((row:any)=><p key={row.currency}>{row.currency}: opening {money(row.openingCents)}, operating {money(row.operatingCents)}, investing {money(row.investingCents)}, financing {money(row.financingCents)}, closing {money(row.closingCents)}</p>)}
 </div></details>;
}
