export function buildCsjOrientationEmailBody(employee: any) {
  const firstName = String(employee?.firstName ?? "").trim() || "there";
  return [
    `Hi ${firstName},`,
    "",
    "Thanks for completing the required documentation, no need to worry about the employee number, we will do that on our end. Since you'll be working primarily remotely, I've gathered some resources that we'll review during your virtual orientation in your first week.",
    "",
    "Young Workers Website",
    "Please review: https://www.ccohs.ca/youngworkers",
    "This covers your rights, health and safety basics, and workplace responsibilities.",
    "",
    "Virtual Health and Safety Orientation",
    "We'll conduct a video call orientation covering remote work safety:",
    "- Home Office Ergonomics: https://www.ccohs.ca/oshanswers/ergonomics/office",
    "- Digital Equipment Safety: We'll review proper setup for your computer, software access, and digital security.",
    "- Remote Emergency Procedures: Contact information, reporting protocols, and what to do in case of power/internet outages.",
    "- Remote Work Safety Checks: Tips for maintaining a safe home workspace.",
    "",
    "Remote Work and Employment Policies",
    "While we don't have formal written policies, we'll discuss expectations for remote work including:",
    "- Harassment Prevention: BC Human Rights Code basics: https://www2.gov.bc.ca/gov/content/justice/human-rights",
    "- Digital Communication Guidelines: Professional expectations for email, messaging, and video calls.",
    "- Conflict Resolution: Virtual open-door policy and how to raise concerns remotely.",
    "- Privacy and Confidentiality: Protecting organizational data when working from home.",
    "- Work Hours and Boundaries: Setting healthy remote work practices.",
    "",
    "BC Employment Standards for Remote Workers",
    "Review your rights: https://www2.gov.bc.ca/gov/content/employment-business/employment-standards-advice/employment-standards",
    "",
    "Additional Remote Work Resources",
    "- Health tips for remote workers: https://www.ccohs.ca/oshanswers/hsprograms/telework.html",
    "- WorkSafeBC remote work guidelines: https://www.worksafebc.com/en/resources/health-safety/information-sheets/working-from-home-guide-keeping-workers-healthy-safe?lang=en",
    "",
    "Please review these resources before our virtual orientation meeting.",
    "",
    "Looking forward to having you join our team!",
    "",
    "Best regards,",
    "",
    "Ahmad Jalil",
  ].join("\n");
}
