import cihrResearchnet from "./data/grantSources/cihr-researchnet.json";
import accelerateOkanagan from "./data/grantSources/accelerate-okanagan.json";
import accelerateip from "./data/grantSources/accelerateip.json";
import bcArtsCouncil from "./data/grantSources/bc-arts-council.json";
import citySurreyCulturalGrants from "./data/grantSources/city-surrey-cultural-grants.json";
import bcAgriculturePrograms from "./data/grantSources/bc-agriculture-programs.json";
import buyBc from "./data/grantSources/buy-bc.json";
import workbcEmployerTrainingGrant from "./data/grantSources/workbc-employer-training-grant.json";
import bcManufacturingJobsFund from "./data/grantSources/bc-manufacturing-jobs-fund.json";
import childcarebcOperatingFunding from "./data/grantSources/childcarebc-operating-funding.json";
import communityFuturesBc from "./data/grantSources/community-futures-bc.json";
import northernDevelopmentInitiativeTrust from "./data/grantSources/northern-development-initiative-trust.json";
import pacificanFunding from "./data/grantSources/pacifican-funding.json";
import innovateBc from "./data/grantSources/innovate-bc.json";
import bcTech from "./data/grantSources/bc-tech.json";
import ubcHatch from "./data/grantSources/ubc-hatch.json";
import sfuVenturelabs from "./data/grantSources/sfu-venturelabs.json";
import webcFinancing from "./data/grantSources/webc-financing.json";
import taccFinancing from "./data/grantSources/tacc-financing.json";
import newRelationshipTrust from "./data/grantSources/new-relationship-trust.json";
import firstNationsCleanEnergyBusinessFund from "./data/grantSources/first-nations-clean-energy-business-fund.json";
import bcTaxCredits from "./data/grantSources/bc-tax-credits.json";
import nrcResearchCollaboration from "./data/grantSources/nrc-research-collaboration.json";
import ventureForCanada from "./data/grantSources/venture-for-canada.json";

// Generated by scripts/generate-grant-source-library.mjs. Edit the JSON files in
// shared/data/grantSources instead of editing this registry by hand.
export const GENERATED_BUILT_IN_GRANT_SOURCES = [
  cihrResearchnet,
  accelerateOkanagan,
  accelerateip,
  bcArtsCouncil,
  citySurreyCulturalGrants,
  bcAgriculturePrograms,
  buyBc,
  workbcEmployerTrainingGrant,
  bcManufacturingJobsFund,
  childcarebcOperatingFunding,
  communityFuturesBc,
  northernDevelopmentInitiativeTrust,
  pacificanFunding,
  innovateBc,
  bcTech,
  ubcHatch,
  sfuVenturelabs,
  webcFinancing,
  taccFinancing,
  newRelationshipTrust,
  firstNationsCleanEnergyBusinessFund,
  bcTaxCredits,
  nrcResearchCollaboration,
  ventureForCanada,
];
