import type { Permission } from "./functions/permissions";

/** UI navigation guidance only. Server handlers independently authorize every
 * query/mutation and document/record. Denied routes must explain access instead
 * of leaving a read-only member at a permanent data-loading placeholder. */
export const INTERFACE_ROUTE_READ_PERMISSIONS: Readonly<Record<string, Permission>> = {
  "/app": "society:read",
  "/app/setup": "society:read",
  "/app/society": "society:read",
  "/app/organization-details": "society:read",
  "/app/org-history": "society:read",
  "/app/portfolio": "society:read",
  "/app/research-library": "society:read",
  "/app/society/new": "society:read",
  "/app/members": "members:read",
  "/app/people-directory": "members:read",
  "/app/people-history": "members:read",
  "/app/point-in-time-register": "settings:read",
  "/app/org-chart": "members:read",
  "/app/directors": "directors:read",
  "/app/employees": "employees:read",
  "/app/committees": "committees:read",
  "/app/meetings": "meetings:read",
  "/app/meetings/offline": "meetings:read",
  "/app/meeting-templates": "meetings:read",
  "/app/meeting-templates/new": "meetings:read",
  "/app/meeting-evidence": "meetings:read",
  "/app/calendar-sync": "meetings:read",
  "/app/minutes": "minutes:read",
  "/app/minute-book": "minutes:read",
  "/app/agendas": "agendas:read",
  "/app/motions": "motions:read",
  "/app/motion-backlog": "motions:read",
  "/app/motion-library": "motions:read",
  "/app/proposals": "motions:read",
  "/app/written-resolutions": "motions:read",
  "/app/proxies": "proxies:read",
  "/app/conflicts": "conflicts:read",
  "/app/attestations": "attestations:read",
  "/app/pipa-training": "attestations:read",
  "/app/auditors": "auditors:read",
  "/app/court-orders": "courtOrders:read",
  "/app/filings": "filings:read",
  "/app/filings/prefill": "filings:read",
  "/app/annual-filings": "filings:read",
  "/app/deadlines": "deadlines:read",
  "/app/compliance-obligations": "deadlines:read",
  "/app/annual-cycle": "deadlines:read",
  "/app/coverage": "deadlines:read",
  "/app/source-model-coverage": "deadlines:read",
  "/app/post-incorporation": "deadlines:read",
  "/app/commitments": "commitments:read",
  "/app/goals": "commitments:read",
  "/app/financials": "financials:read",
  "/app/financials/accounting": "financials:read",
  "/app/financials/year-end": "financials:read",
  "/app/treasurer": "financials:read",
  "/app/reconciliation": "financials:read",
  "/app/receipts": "financials:read",
  "/app/assets": "financials:read",
  "/app/inventory": "financials:read",
  "/app/insurance": "financials:read",
  "/app/dividends": "financials:read",
  "/app/elections": "elections:read",
  "/app/grants": "grants:read",
  "/app/grants/sources": "grants:read",
  "/app/documents": "documents:read",
  "/app/document-catalog": "documents:read",
  "/app/library": "documents:read",
  "/app/records-archive": "documents:read",
  "/app/governance-registers": "documents:read",
  "/app/policies": "documents:read",
  "/app/privacy": "documents:read",
  "/app/bylaw-diff": "documents:read",
  "/app/bylaw-rules": "documents:read",
  "/app/bylaws-history": "documents:read",
  "/app/role-holders": "documents:read",
  "/app/rights-ledger": "documents:read",
  "/app/template-engine": "documents:read",
  "/app/formation-maintenance": "documents:read",
  "/app/certificate-register": "documents:read",
  "/app/inspections": "documents:read",
  "/app/retention": "documents:read",
  "/app/users": "society:read",
  "/app/membership": "settings:read",
  "/app/tasks": "tasks:read",
  "/app/timeline": "tasks:read",
  "/app/notifications": "tasks:read",
  "/app/workflows": "tasks:read",
  "/app/workflow-runs": "tasks:read",
  "/app/workflow-packages": "tasks:read",
  "/app/integrations": "settings:read",
  "/app/ai-agents": "tasks:read",
  "/app/outbox": "communications:read",
  "/app/exports": "exports:read",
  "/app/audit": "audit:read",
  "/app/volunteers": "volunteers:read",
  "/app/communications": "communications:read",
  "/app/compliance-settings": "settings:read",
  "/app/corporate-history": "settings:read",
  "/app/significant-individuals": "settings:read",
  "/app/service-providers": "settings:read",
  "/app/finance-imports": "settings:read",
  "/app/imports": "settings:read",
  "/app/intake": "settings:read",
  "/app/financials/wave": "settings:read",
  "/app/access-custody": "settings:read",
  "/app/secrets": "settings:read",
  "/app/transparency": "settings:read",
  "/app/paperless": "settings:read",
  "/app/browser-connectors": "settings:read",
  "/app/custom-fields": "settings:read",
  "/app/table-field-lab": "settings:read",
  "/app/settings": "settings:read",
  "/app/settings/api-keys": "settings:read",
  "/app/webhooks": "settings:read"
};

export function interfaceRouteReadPermission(pathname: string): Permission | undefined {
  let decoded = pathname;
  try { decoded = decodeURIComponent(pathname); } catch { /* Match malformed paths without throwing in the shell. */ }
  // React Router's static routes are case insensitive and decode URL segments.
  const path = decoded.toLowerCase().replace(/\/+$/, "") || "/";
  const match = Object.keys(INTERFACE_ROUTE_READ_PERMISSIONS)
    .sort((left, right) => right.length - left.length)
    .find((prefix) => path === prefix || (prefix !== "/app" && path.startsWith(`${prefix}/`)));
  return match ? INTERFACE_ROUTE_READ_PERMISSIONS[match] : undefined;
}
