import assert from "node:assert/strict";
import JSZip from "jszip";
import { archiveDatabaseSnapshot, buildWorkspaceArchive, hashBytes, readWorkspaceArchiveFile } from "../src/lib/workspaceArchive";
import { LocalDexieRowStore } from "../src/lib/localDexieRowStore";
import { archiveFileRows } from "../src/lib/workspaceArchiveFiles";
const database = { kind: "societyer.localWorkspaceSnapshot", exportedAtISO: "2026-10-06T12:00:00Z", tables: { societies: [{ _id: "s1", name: "Archive test" }], minutes: [{ _id: "m1", societyId: "s1", text: "µg/m³ · source wording", sourceMeetingRecord: { documents: [] } }] }, attachments: [], changes: [{ table: "minutes", id: "m1", op: "upsert", createdAtISO: "2026-10-06T11:00:00Z", snapshot: { text: "Earlier wording" } }] };
const content = new TextEncoder().encode("Exact original file bytes");
const result = await buildWorkspaceArchive(database, async add => {
 await add({ fileName: "../original.doc", provider: "local-filesystem", storageKey: "source/key", documentId: "d1", versionId: "v1", status: "included" }, new Blob([content]));
 await add({ fileName: "second-name.doc", status: "included" }, new Blob([content]));
 await add({ fileName: "external.pdf", status: "external", externalUrl: "https://example.com/source.pdf" });
 await add({ fileName: "missing.pdf", status: "unavailable", reason: "Not on this device" });
});
assert.equal(result.manifest.includedFiles, 1); assert.equal(result.manifest.externalFiles, 1); assert.equal(result.manifest.unavailableFiles, 1); assert.equal(result.manifest.completeStoredFiles, false);
assert.ok(!result.manifest.files[0].archivePath?.split("/").includes(".."));
const restored = await readWorkspaceArchiveFile(new File([result.blob], "backup.zip"));
assert.deepEqual(restored.database, database); assert.equal(restored.files.size, 1); assert.equal(await hashBytes(await restored.files.values().next().value!.arrayBuffer()), await hashBytes(content));
const local = new LocalDexieRowStore({});
const sha256 = await hashBytes(content);
await local.importSnapshot(archiveDatabaseSnapshot(restored.database), archiveFileRows(restored.manifest, restored.files));
assert.equal(await (await local.readRestoredFile({ provider: "local-filesystem", storageKey: "source/key" }))!.text(), "Exact original file bytes");
assert.equal(await (await local.readRestoredFile({ documentId: "d1" }))!.text(), "Exact original file bytes");
assert.equal(await (await local.readRestoredFile({ versionId: "v1" }))!.text(), "Exact original file bytes");
assert.deepEqual(local.exportSnapshot().changes[0].snapshot, database.changes[0].snapshot);
await local.importSnapshot(local.exportSnapshot(), undefined, true);
assert.equal(await (await local.readRestoredFile({ documentId: "d1" }))!.text(), "Exact original file bytes");
const before = local.exportSnapshot().tables;
await assert.rejects(local.importSnapshot({ ...database, changes: [{ bad: true }] } as any), /change history/); assert.deepEqual(local.exportSnapshot().tables, before);
const legacy = new JSZip(); legacy.file("legacy-backup.json", JSON.stringify(database)); legacy.file("summary.json", "{}");
assert.deepEqual((await readWorkspaceArchiveFile(new File([await legacy.generateAsync({ type: "uint8array" })], "old.zip"))).database, database);
assert.deepEqual((await readWorkspaceArchiveFile(new File([JSON.stringify(database)], "old.json"))).database, database);
const exported = archiveDatabaseSnapshot({ kind: "societyer.workspaceExport", generatedAtISO: database.exportedAtISO, tables: database.tables }); assert.equal(exported.kind, database.kind);
const tampered = await JSZip.loadAsync(await result.blob.arrayBuffer()); tampered.file("workspace.json", JSON.stringify({ ...database, tables: {} }));
await assert.rejects(readWorkspaceArchiveFile(new File([await tampered.generateAsync({ type: "uint8array" })], "damaged.zip")), /checksum/);
const damagedFile = await JSZip.loadAsync(await result.blob.arrayBuffer()); damagedFile.file(result.manifest.files[0].archivePath!, "different bytes");
await assert.rejects(readWorkspaceArchiveFile(new File([await damagedFile.generateAsync({ type: "uint8array" })], "damaged-file.zip")), /checksum/);
const unsafe = new JSZip(); unsafe.file("../escape.json", JSON.stringify(database));
await assert.rejects(readWorkspaceArchiveFile(new File([await unsafe.generateAsync({ type: "uint8array" })], "unsafe.zip")), /invalid file path/);
const wrongAlias = await JSZip.loadAsync(await result.blob.arrayBuffer());
const aliasManifest = JSON.parse(await wrongAlias.file("manifest.json")!.async("string"));
aliasManifest.files[1].archivePath = "files/unchecked-alias";
wrongAlias.file("files/unchecked-alias", "corrupted alias bytes");
wrongAlias.file("manifest.json", JSON.stringify(aliasManifest));
await assert.rejects(readWorkspaceArchiveFile(new File([await wrongAlias.generateAsync({ type: "uint8array" })], "alias.zip")), /inconsistent file aliases/);
console.log("ZIP archive checks passed: exact records/files, deduplication, external/missing inventory, legacy JSON/ZIP, preserved journal, corruption/path rejection and invalid-import atomicity.");
