import assert from "node:assert/strict";
import { evaluateLegalDecision, legalMeetingQuorum } from "../shared/legalDecision";
import { motionCarriesByType } from "../src/lib/motionGovernance";
import { addComplianceDateOffset, complianceFactsForOrganization, computeComplianceObligations } from "../src/lib/compliance";
const written = { jurisdiction: "CA-BC", entityType: "society", body: "members", mode: "written", resolution: "ordinary", votesFor: 2, votesAgainst: 0, eligibleVotes: 3, circulatedToAll: true, governingInstrumentEvidence: "Filed bylaws v1 and electorate register" } as const;
assert.equal(evaluateLegalDecision(written).carries, true);
assert.equal(evaluateLegalDecision({ ...written, votesFor: 60, eligibleVotes: 100 }).carries, false);
assert.equal(evaluateLegalDecision({ ...written, resolution: "special" }).carries, false);
assert.equal(evaluateLegalDecision({ ...written, circulatedToAll: false }).carries, null);
assert.equal(evaluateLegalDecision({ ...written, body: "directors", votesFor: 2 }).carries, null);
assert.equal(evaluateLegalDecision({ ...written, mode: "meeting", votesFor: 2, votesAgainst: 1, quorumMet: true }).carries, true);
assert.equal(evaluateLegalDecision({ ...written, mode: "meeting", votesFor: 1, votesAgainst: 1, quorumMet: true }).carries, false);
assert.equal(evaluateLegalDecision({ ...written, votesFor: 3, deemedAgm: true, financialStatementsProvided: false, annualBusinessComplete: true }).carries, null);
assert.equal(evaluateLegalDecision({ ...written, votesFor: 3, deemedAgm: true, financialStatementsProvided: true, annualBusinessComplete: true }).carries, true);
assert.equal(evaluateLegalDecision({ ...written, entityType: "corporation__business_", body: "shareholders" }).carries, true);
assert.equal(evaluateLegalDecision({ ...written, entityType: "corporation__business_", body: "shareholders", jurisdiction: "CA-FED-CBCA" }).carries, false);
assert.equal(evaluateLegalDecision({ ...written, entityType: "corporation__business_", body: "shareholders", jurisdiction: "CA-ON-OBCA", votesFor: 3 }).carries, null);
assert.equal(legalMeetingQuorum({ entityType: "society", jurisdiction: "CA-BC", eligiblePeople: 2, presentPeople: 2 }).met, true);
assert.equal(legalMeetingQuorum({ entityType: "society", jurisdiction: "CA-BC", eligiblePeople: 41, presentPeople: 4, adoptedModel: "bc_society" }).met, false);
assert.equal(legalMeetingQuorum({ entityType: "corporation__business_", jurisdiction: "CA-BC", eligiblePeople: 10, presentPeople: 2, adoptedModel: "bc_table_1", eligibleVotingShares: 100, presentVotingShares: 4 }).met, false);
assert.equal(legalMeetingQuorum({ entityType: "corporation__business_", jurisdiction: "CA-BC", eligiblePeople: 10, presentPeople: 2, adoptedModel: "bc_table_1", eligibleVotingShares: 100, presentVotingShares: 5 }).met, true);
assert.equal(motionCarriesByType({ votesFor: 2, votesAgainst: 1 }, { id: "all", label: "All", thresholdPct: 66.67, base: "eligibleMembers" }), null);
assert.equal(addComplianceDateOffset("2024-02-29", { years: 1 }), "2025-02-28");
assert.equal(addComplianceDateOffset("2026-01-31", { months: 2 }), "2026-03-31");
const company = { jurisdictionCode: "CA-BC", entityType: "corporation__business_", incorporationDate: "2022-03-01", anniversaryDate: "2022-03-01", asOfDate: "2026-07-01" };
assert.deepEqual(computeComplianceObligations({ ...company, formationStatus: "preparing" }), []);
assert.deepEqual(computeComplianceObligations({ ...company, formationStatus: "submitted" }), []);
const annuals = computeComplianceObligations(company).filter(o => o.ruleId === "compliance-ca-bc-company-annual-report");
assert.deepEqual(annuals.map(o => o.dueDate), ["2023-05-01", "2024-05-01", "2025-05-01", "2026-05-01"]);
assert.equal(new Set(annuals.map(o => o.occurrenceKey)).size, 4);
assert.equal(annuals.every(o => o.status === "overdue"), true);
const federal = { ...company, jurisdictionCode: "CA-FED-CBCA", incorporationDate: "2026-01-31", eventDates: { continuanceDate: "2026-02-01", iscAwarenessDate: "2026-02-10", iscRegisterEntryDate: "2026-02-20" } };
const federalRules = new Map(computeComplianceObligations(federal).map(o => [o.ruleId, o]));
assert.equal(federalRules.get("compliance-ca-fed-cbca-initial-isc-filing")?.dueDate, "2026-01-31");
assert.equal(federalRules.get("compliance-ca-fed-cbca-continuance-isc-filing")?.dueDate, "2026-03-03");
assert.equal(federalRules.get("compliance-ca-fed-cbca-isc-register-update")?.dueDate, "2026-02-25");
assert.equal(federalRules.get("compliance-ca-fed-cbca-isc-change-filing")?.dueDate, "2026-03-07");
const org = { ...company, fiscalYearEnd: "12-31" };
const registration = { _id: "on", jurisdiction: "CA-ON-OBCA", registrationDate: "2026-01-01", activityCommencementDate: "2026-02-01" };
const regFacts = complianceFactsForOrganization(org, { asOfDate: "2026-03-01", registrations: [registration] })[1];
assert.equal(regFacts.incorporationDate, "2022-03-01");
assert.equal(computeComplianceObligations(regFacts).find(o => o.ruleId === "compliance-ca-on-extra-provincial-initial-return")?.dueDate, "2026-04-02");
assert.equal(computeComplianceObligations({ ...regFacts, commencedBusinessDate: undefined }).some(o => o.ruleId === "compliance-ca-on-extra-provincial-initial-return"), false);
assert.equal(computeComplianceObligations(regFacts).some(o => o.obligationKey === "registry.annual_return"), false);
const society = { ...company, entityType: "society", incorporationDate: "2026-01-01" };
assert.equal(computeComplianceObligations(society).some(o => o.ruleId === "compliance-ca-bc-societies-agm-planning"), false);
const existingSociety = { ...society, incorporationDate: "2020-01-01", asOfDate: "2027-01-15", annualMeetingDate: "2026-12-31" };
assert.equal(computeComplianceObligations(existingSociety).find(o => o.ruleId === "compliance-ca-bc-societies-annual-report")?.dueDate, "2027-01-30");
assert.equal(computeComplianceObligations({ ...existingSociety, annualMeetingDate: undefined }).find(o => o.ruleId === "compliance-ca-bc-societies-no-agm-annual-report")?.dueDate, "2027-01-31");
assert.equal(computeComplianceObligations({ ...existingSociety, annualMeetingDate: "2027-02-01", annualMeetingYear: 2026, agmExtensionDate: "2027-02-15", agmExtensionEvidence: "Registrar approval" }).some(o => o.ruleId === "compliance-ca-bc-societies-no-agm-annual-report"), false);
console.log("Research legal boundary checks passed: modes, electorates, clear statutory anchors, overdue history and month/leap dates.");
