import assert from "node:assert/strict";
import { bylawBaselineForOrganization, clearNoticeDays, contextualBylawRules } from "../shared/bylawBaselines";
import { noticeWindowSatisfied } from "../src/features/meetings/lib/noticeWindow";
import { computedQuorumMet } from "../src/features/meetings/lib/meetingDetailHelpers";
import { StaticConvexClient } from "../src/lib/staticConvex";
assert.equal(bylawBaselineForOrganization({ entityType: "society", jurisdictionCode: "CA-FED-CBCA" }, "wrong").governanceAutomationBlocked, true);
assert.equal(bylawBaselineForOrganization({ entityType: "corporation__non_profit_", jurisdictionCode: "CA-BC" }, "nfp").governanceAutomationBlocked, true);
assert.equal(bylawBaselineForOrganization({}, "unknown").governanceAutomationBlocked, true);
assert.equal(bylawBaselineForOrganization({ incorporationNumber: "S1234", name: "Legacy BC society" }, "legacy").governanceAutomationBlocked, false);
assert.equal(bylawBaselineForOrganization({ entityType: "corporation__business_", homeJurisdiction: "federal__canada_" }, "alias").jurisdictionCode, "CA-FED-CBCA");
const society = bylawBaselineForOrganization({ entityType: "society", jurisdictionCode: "CA-BC" }, "society");
assert.equal(society.quorumType, "fixed");
assert.equal(society.quorumValue, 3, "statutory society fallback cannot assert adopted model's 10% clause");
assert.equal(society.isFallback, true);
const bc = bylawBaselineForOrganization({ entityType: "corporation__business_", jurisdictionCode: "CA-BC" }, "bc");
assert.equal(bc.generalNoticeMinDays, 21);
assert.equal(bc.quorumValue, 2);
assert.equal(bc.quorumDenominator, "legal_shareholders");
assert.equal(bc.noticeUsesCalendarMonthsMaximum, true);
const fed = bylawBaselineForOrganization({ entityType: "corporation__business_", jurisdictionCode: "CA-FED-CBCA" }, "fed");
assert.equal(fed.generalNoticeMinDays, 21);
assert.equal(fed.quorumDenominator, "issued_voting_shares");
assert.equal(fed.quorumRequiresLegalRegister, true);
assert.equal(bylawBaselineForOrganization({ entityType: "corporation__business_", jurisdictionCode: "CA-ON-OBCA" }, "on").governanceAutomationBlocked, true);
assert.equal(clearNoticeDays("2026-07-13", "2026-07-27"), 13);
assert.equal(clearNoticeDays("2026-07-13", "2026-07-28"), 14);
assert.equal(clearNoticeDays("2026-03-07", "2026-03-23"), 15, "DST does not reduce full calendar days");
assert.equal(clearNoticeDays("2026-02-30", "2026-03-23"), null);
assert.equal(noticeWindowSatisfied("2026-07-13T23:59:00", "2026-07-27T09:00:00", 14, 60, society), false);
assert.equal(noticeWindowSatisfied("2026-07-13T23:59:00", "2026-07-28T09:00:00", 14, 60, society), true);
assert.equal(noticeWindowSatisfied("2026-01-01T09:00:00", "2026-03-02T09:00:00", 21, 62, bc), false, "two calendar months cannot be replaced with 62 days");
assert.equal(noticeWindowSatisfied("2026-01-31T09:00:00", "2026-03-31T09:00:00", 21, 62, bc), true);
assert.equal(contextualBylawRules({ entityType: "corporation__business_", jurisdictionCode: "CA-FED-CBCA" }, "fed", { _id: "old", status: "Active", quorumType: "percentage", quorumValue: 10 }).quorumRequiresLegalRegister, true, "legacy corporation society-style rules cannot confer member-headcount quorum");
assert.equal(computedQuorumMet({ presentCount: 100, required: 3, requiresLegalRegister: true }), null, "workspace attendance cannot establish corporate share electorate quorum");
const client = new StaticConvexClient({ databaseName: `jurisdiction-baselines-${Date.now()}`, seed: { societies: [] } });
const created = await client.mutation("society:createWorkspace", { name: "Federal quorum evidence test", incorporationDate: "2026-01-01", incorporationNumber: "123", fiscalYearEnd: "12-31", entityType: "corporation__business_", jurisdictionCode: "CA-FED-CBCA", actFormedUnder: "canada_business_corporations_act" });
let active = await client.query("bylawRules:getActive", { societyId: created.societyId });
assert.equal(active.generalNoticeMinDays, 21);
assert.equal(active.quorumRequiresLegalRegister, true);
assert.equal(active.isFallback, true);
const meetingId = await client.mutation("meetings:create", { societyId: created.societyId, type: "AGM", title: "Shareholders AGM", scheduledAt: "2027-06-01T12:00:00Z", electronic: false, status: "Scheduled", attendeeIds: [] });
const meeting = await client.query("meetings:get", { id: meetingId });
assert.equal(meeting.quorumRequired, undefined, "corporation quorum remains unknown without legal share electorate, regardless of app member count");
assert.match(meeting.quorumSourceLabel, /CBCA/);
await client.mutation("bylawRules:resetToDefault", { societyId: created.societyId });
active = await client.query("bylawRules:getActive", { societyId: created.societyId });
assert.equal(active.isFallback, true);
assert.equal(active._id, undefined, "reset does not manufacture adopted operative bylaws");
const history = await client.query("bylawRules:list", { societyId: created.societyId });
assert.equal(history.at(-1).status, "Baseline", "reset has an audit marker");
console.log("Jurisdiction-aware bylaw baselines, share-quorum gates, reset provenance and clear/calendar-month notice boundary checks passed.");
